
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        exclude: |
          (?x)^(
              ^(Core/|Lib/|cmake/).*\.(c|cpp|h|hpp)$ |
              ^Drivers/(CMSIS/|STM32H7xx_HAL_Driver/).*\.(c|cpp|h|hpp)$ |   
          )$
