#pragma once
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpsabi" // Suppress: parameter passing for argument of type 'Time::DefaultCUC' {aka 'TimeStamp<4, 0, 1, 10>'} changed in GCC 7.1
#include "Helpers/Parameter.hpp"
namespace OBDHParameters {
    enum ParameterID : uint16_t {
        PCBTemperature1ID = 5010,
        PCBTemperature2ID = 5020,
        MCUTemperatureID = 5030,
        MCUInputVoltageID = 5031,
        MCUSystickID = 5032,
        LastFailedEventID = 5033,
        MCUBootCounterID = 5040,
        OperationalModeID = 5041,
        SpacecraftTimeRefID = 5100,
        ReconfigurationTimerID = 5101,
        OnBoardTimeID = 5120,
        CANBUSLoad1ID = 5180,
        CANBUSLoad2ID = 5190,
        CANBUSActiveID = 5200,
        MCUFDIRID = 5210,
        MCURestartSafeModeThresholdID = 5220,
        NANDFLASHLCLThresholdID = 5230,
        MRAMLCLThresholdID = 5240,
        NANDFLASHONID = 5250,
        MRAMONID = 5260,
        FlashIntID = 5261,
        SRAMIntID = 5262,
        AvailableMRAMID = 5263,
        AvailableNANDID = 5264,
        MemoryPartitionID = 5265,
        NANDFLASHScrubbingFrequencyID = 5270,
        ΜRAMScrubbingFrequencyID = 5280,
        ProgramFlashScrubbingFrequencyID = 5290,
        CommitHashID = 5330,
        CAN_ACK_timeoutID = 5340,
        CAN_FrameRetransimtCountID = 5350,
        CAN_TransmitFailureCountID = 5360,
        UseRTTID = 5370,
        UseUARTID = 5380,
        UseCANID = 5390
    };
    inline Parameter<float> PCBTemperature1(0);
    inline Parameter<float> PCBTemperature2(0);
    inline Parameter<float> MCUTemperature(0);
    inline Parameter<float> MCUInputVoltage(0);
    inline Parameter<uint32_t> MCUSystick(0);
    inline Parameter<uint16_t> LastFailedEvent(0);
    inline Parameter<uint16_t> MCUBootCounter(0);
    enum OperationalMode_enum : uint8_t {
        CommissioningMode = 0,
        NominalMode = 1,
        ScienceMode = 2,
        SafeMode = 3
    };
    inline Parameter<OperationalMode_enum> OperationalMode(NominalMode);
    enum SpacecraftTimeRef_enum : uint8_t {
        Spacecraft = 0,
        GroundStation = 1
    };
    inline Parameter<SpacecraftTimeRef_enum> SpacecraftTimeRef(Spacecraft);
    inline Parameter<uint32_t> ReconfigurationTimer(0);
    inline Parameter<Time::DefaultCUC> OnBoardTime(Time::DefaultCUC(0));
    inline Parameter<float> CANBUSLoad1(0);
    inline Parameter<float> CANBUSLoad2(0);
    enum CANBUSActive_enum : uint8_t {
        Main = 0,
        Redundant
    };
    inline Parameter<CANBUSActive_enum> CANBUSActive(Main);
    enum MCUFDIR_enum : uint8_t {
        OBC = 0,
        ADCS = 1
    };
    inline Parameter<MCUFDIR_enum> MCUFDIR(OBC);
    inline Parameter<uint8_t> MCURestartSafeModeThreshold(0);
    inline Parameter<float> NANDFLASHLCLThreshold(0);
    inline Parameter<float> MRAMLCLThreshold(0);
    inline Parameter<bool> NANDFLASHON(true);
    inline Parameter<bool> MRAMON(true);
    inline Parameter<uint32_t> FlashInt(0);
    inline Parameter<uint32_t> SRAMInt(0);
    inline Parameter<uint32_t> AvailableMRAM(0);
    inline Parameter<uint32_t> AvailableNAND(0);
    enum MemoryPartition_enum : uint8_t {
        First = 0,
        Second = 1
    };
    inline Parameter<MemoryPartition_enum> MemoryPartition(First);
    inline Parameter<float> NANDFLASHScrubbingFrequency(0);
    inline Parameter<float> ΜRAMScrubbingFrequency(0);
    inline Parameter<float> ProgramFlashScrubbingFrequency(0);
    inline Parameter<uint16_t> CommitHash(0);
    inline Parameter<uint32_t> CAN_ACK_timeout(0);
    inline Parameter<uint32_t> CAN_FrameRetransimtCount(0);
    inline Parameter<uint32_t> CAN_TransmitFailureCount(0);
    inline Parameter<bool> UseRTT(true);
    inline Parameter<bool> UseUART(true);
    inline Parameter<bool> UseCAN(false);
} // namespace OBDHParameters
namespace COMMSParameters {
    enum ParameterID : uint16_t {
        commsUHFBandPATemperatureID = 10010,
        commsPCBTemperatureID = 10020,
        commsGNSSTemperatureID = 10030,
        Antenna_Deployment_StatusID = 10050,
        commit_hashID = 10350
    };
    inline Parameter<float> commsUHFBandPATemperature(0);
    inline Parameter<float> commsPCBTemperature(0);
    inline Parameter<float> commsGNSSTemperature(0);
    enum Antenna_Deployment_Status_enum : uint8_t {
        Closed = 0,
        OneDoorOpen = 1,
        TwoDoorOpen = 2,
        ThreeDoorOpen = 3,
        FullyDeployed = 4
    };
    inline Parameter<Antenna_Deployment_Status_enum> Antenna_Deployment_Status(Closed);
    inline Parameter<uint16_t> commit_hash(0);
} // namespace COMMSParameters
namespace PAYParameters {
    enum ParameterID : uint16_t {
        xID = 15010,
        yID = 15020,
        zID = 15030,
        uptimeID = 15040,
        timeID = 15050,
        psu_12vID = 15060,
        psu_5vID = 15070,
        psu_33vID = 15080,
        mcu_die_temperatureID = 15090,
        main_board_temperatureID = 15100,
        seed_ld_output_powerID = 15110,
        fsm_chamber_temperatureID = 15120,
        fsm_chamber_pressureID = 15130,
        fsmd_voltage_converter_temperatureID = 15140,
        fsmd_drivers_temperatureID = 15150,
        camera_pcb_temperatureID = 15160,
        camera_sensor_temperatureID = 15170,
        fso_aux_temperature_1ID = 15171,
        fso_aux_temperature_2ID = 15172,
        oad_temperatureID = 15180,
        optical_amplifier_combiner_heater_temperatureID = 15181,
        optical_amplifier_fiber_mirror_temperatureID = 15182,
        optical_amplifier_circulator_heater_temperatureID = 15183,
        ldd_temperatureID = 15190,
        ld_temperatureID = 15200,
        ldd_12v_currentID = 15210,
        ldd_psu_12vID = 15211,
        ldd_converter_input_currentID = 15212,
        ldd_ld_vID = 15213,
        ldd_ld_dac_set_vID = 15214,
        fsm_driver_12v_currentID = 15220,
        flashes_33v_currentID = 15230,
        fpga_5v_currentID = 15240,
        sdd_33v_currentID = 15250,
        pump_ld_powerID = 15260,
        mcu_33v_currentID = 15270,
        fpga_die_temperatureID = 15280,
        fpga_vdd1_voltageID = 15290,
        fpga_vdd18_voltageID = 15300,
        fpga_vdd25_voltageID = 15310,
        seed_ld_incoming_powerID = 15320,
        amplifier_output_powerID = 15321,
        amplifier_output_reflected_powerID = 15322,
        seed_diode_bias_currentID = 15323,
        tec_currentID = 15330,
        ldd_output_currentID = 15340,
        sd_temperature_violationsID = 15341,
        end_uptimeID = 15350,
        responseID = 15360,
        deviceID = 15390,
        firmwareID = 15400,
        firmware_is_confirmedID = 15410,
        bitstreamID = 15420,
        softcpu_1_firmwareID = 15430,
        softcpu_2_firmwareID = 15440,
        softcpu_3_firmwareID = 15450,
        softcpu_4_firmwareID = 15460,
        softcpu_5_firmwareID = 15470,
        softcpu_6_firmwareID = 15480,
        softcpu_7_firmwareID = 15490,
        softcpu_8_firmwareID = 15500,
        boot_countID = 15510,
        transmission_countID = 15520,
        hw_detID = 15530,
        storage0ID = 15540,
        storage1ID = 15550,
        storage2ID = 15560,
        storage3ID = 15570,
        ldd_faultID = 15580,
        fsm_faultID = 15590,
        fpga_faultID = 15600,
        v_cam_faultID = 15620,
        sdd_faultID = 15630
    };
    inline Parameter<int32_t> x(0);
    inline Parameter<int32_t> y(0);
    inline Parameter<int32_t> z(0);
    inline Parameter<int32_t> uptime(0);
    inline Parameter<int32_t> time(0);
    inline Parameter<int32_t> psu_12v(0);
    inline Parameter<int32_t> psu_5v(0);
    inline Parameter<int32_t> psu_33v(0);
    inline Parameter<int32_t> mcu_die_temperature(0);
    inline Parameter<int32_t> main_board_temperature(0);
    inline Parameter<int32_t> seed_ld_output_power(0);
    inline Parameter<int32_t> fsm_chamber_temperature(0);
    inline Parameter<int32_t> fsm_chamber_pressure(0);
    inline Parameter<int32_t> fsmd_voltage_converter_temperature(0);
    inline Parameter<int32_t> fsmd_drivers_temperature(0);
    inline Parameter<int32_t> camera_pcb_temperature(0);
    inline Parameter<int32_t> camera_sensor_temperature(0);
    inline Parameter<int32_t> fso_aux_temperature_1(0);
    inline Parameter<int32_t> fso_aux_temperature_2(0);
    inline Parameter<int32_t> oad_temperature(0);
    inline Parameter<int32_t> optical_amplifier_combiner_heater_temperature(0);
    inline Parameter<int32_t> optical_amplifier_fiber_mirror_temperature(0);
    inline Parameter<int32_t> optical_amplifier_circulator_heater_temperature(0);
    inline Parameter<int32_t> ldd_temperature(0);
    inline Parameter<int32_t> ld_temperature(0);
    inline Parameter<int32_t> ldd_12v_current(0);
    inline Parameter<int32_t> ldd_psu_12v(0);
    inline Parameter<int32_t> ldd_converter_input_current(0);
    inline Parameter<int32_t> ldd_ld_v(0);
    inline Parameter<int32_t> ldd_ld_dac_set_v(0);
    inline Parameter<int32_t> fsm_driver_12v_current(0);
    inline Parameter<int32_t> flashes_33v_current(0);
    inline Parameter<int32_t> fpga_5v_current(0);
    inline Parameter<int32_t> sdd_33v_current(0);
    inline Parameter<int32_t> pump_ld_power(0);
    inline Parameter<int32_t> mcu_33v_current(0);
    inline Parameter<int32_t> fpga_die_temperature(0);
    inline Parameter<int32_t> fpga_vdd1_voltage(0);
    inline Parameter<int32_t> fpga_vdd18_voltage(0);
    inline Parameter<int32_t> fpga_vdd25_voltage(0);
    inline Parameter<int32_t> seed_ld_incoming_power(0);
    inline Parameter<int32_t> amplifier_output_power(0);
    inline Parameter<int32_t> amplifier_output_reflected_power(0);
    inline Parameter<int32_t> seed_diode_bias_current(0);
    inline Parameter<int32_t> tec_current(0);
    inline Parameter<int32_t> ldd_output_current(0);
    inline Parameter<int32_t> sd_temperature_violations(0);
    inline Parameter<int32_t> end_uptime(0);
    inline Parameter<int32_t> response(0);
    inline Parameter<int32_t> device(0);
    inline Parameter<int32_t> firmware(0);
    inline Parameter<int32_t> firmware_is_confirmed(0);
    inline Parameter<int32_t> bitstream(0);
    inline Parameter<int32_t> softcpu_1_firmware(0);
    inline Parameter<int32_t> softcpu_2_firmware(0);
    inline Parameter<int32_t> softcpu_3_firmware(0);
    inline Parameter<int32_t> softcpu_4_firmware(0);
    inline Parameter<int32_t> softcpu_5_firmware(0);
    inline Parameter<int32_t> softcpu_6_firmware(0);
    inline Parameter<int32_t> softcpu_7_firmware(0);
    inline Parameter<int32_t> softcpu_8_firmware(0);
    inline Parameter<int32_t> boot_count(0);
    inline Parameter<int32_t> transmission_count(0);
    inline Parameter<int32_t> hw_det(0);
    inline Parameter<int32_t> storage0(0);
    inline Parameter<int32_t> storage1(0);
    inline Parameter<int32_t> storage2(0);
    inline Parameter<int32_t> storage3(0);
    inline Parameter<int32_t> ldd_fault(0);
    inline Parameter<int32_t> fsm_fault(0);
    inline Parameter<int32_t> fpga_fault(0);
    inline Parameter<int32_t> v_cam_fault(0);
    inline Parameter<int32_t> sdd_fault(0);
} // namespace PAYParameters
namespace ADCSParameters {
    enum ParameterID : uint16_t {
        ResetTypeID = 20010,
        EstRpyRollID = 20030,
        EstRpyPitchID = 20040,
        EstRpyYawID = 20050,
        EstRateIrcXID = 20060,
        EstRateIrcYID = 20070,
        EstRateIrcZID = 20080,
        EstStdDevQ0ID = 20420,
        EstStdDevQ1ID = 20430,
        EstStdDevQ2ID = 20440,
        Str0Quat1ID = 20740,
        Str0Quat2ID = 20750,
        Str0Quat3ID = 20760,
        Str0Quat4ID = 20770,
        Str0AngVelXID = 20780,
        Str0AngVelYID = 20790,
        Str0AngVelZID = 20800,
        ConModeSelectID = 20300,
        ConModeDefaultID = 20301,
        RWL0_power_stateID = 20801,
        RWL1_power_stateID = 20802,
        RWL2_power_stateID = 20803,
        Mag0PowerID = 20804,
        Gyro0PowerID = 20805,
        Gyro1PowerID = 20806,
        Fss0PowerID = 20807,
        Hss0PowerID = 20808,
        Str0PowerID = 20809,
        SatPosEciXID = 20090,
        SatPosEciYID = 20100,
        SatPosEciZID = 20110,
        SatVelEciXID = 20120,
        SatVelEciYID = 20130,
        SatVelEciZID = 20140,
        TgtTrackBodyVecXID = 20680,
        TgtTrackBodyVecYID = 20690,
        TgtTrackBodyVecZID = 20700,
        TgtRefLatID = 20710,
        TgtRefLonID = 20720,
        TgtRefAltID = 20730
    };
    enum ResetType_enum : uint8_t {
        DoNothng = 0,
        Soft = 55,
        Hard = 66
    };
    inline Parameter<ResetType_enum> ResetType(DoNothng);
    inline Parameter<int16_t> EstRpyRoll(0);
    inline Parameter<int16_t> EstRpyPitch(0);
    inline Parameter<int16_t> EstRpyYaw(0);
    inline Parameter<int16_t> EstRateIrcX(0);
    inline Parameter<int16_t> EstRateIrcY(0);
    inline Parameter<int16_t> EstRateIrcZ(0);
    inline Parameter<int16_t> EstStdDevQ0(0);
    inline Parameter<int16_t> EstStdDevQ1(0);
    inline Parameter<int16_t> EstStdDevQ2(0);
    inline Parameter<float> Str0Quat1(0);
    inline Parameter<float> Str0Quat2(0);
    inline Parameter<float> Str0Quat3(0);
    inline Parameter<float> Str0Quat4(0);
    inline Parameter<uint16_t> Str0AngVelX(0);
    inline Parameter<uint16_t> Str0AngVelY(0);
    inline Parameter<uint16_t> Str0AngVelZ(0);
    enum ConModeSelect_enum : uint8_t {
        ConNone = 0,
        ConBdot = 1,
        ConYspin = 2,
        ConBdot3 = 3,
        ConDetumble = 4,
        ConSunYspin = 5,
        ConZspin = 6,
        ConSunZspin = 7,
        ConGGboom = 8,
        ConGGsun = 9,
        ConYwheelInit = 10,
        ConYwheel = 11,
        ConXYZwheel = 12,
        ConSunTrack = 13,
        ConTgtTrack = 14,
        ConTgtSteer = 15,
        ConGndTrack = 16,
        ConIrcTrack = 17,
        ConMoonTrack = 18,
        ConSatTrack = 19,
        ConYawSun = 20,
        ConYawTarget = 21,
        ConRollSun = 22,
        ConRollTarget = 23,
        ConYawTargetBest = 24,
        ConFmcTarget = 25,
        ConYawSunSpin = 26,
        ConSunDetumble = 27,
        ConAstroSteer = 28,
        ConSunPayload = 29,
        ConStopRW = 50,
        ConHxyzRW = 51,
        ConUser = 100
    };
    inline Parameter<ConModeSelect_enum> ConModeSelect(ConNone);
    inline Parameter<ConModeSelect_enum> ConModeDefault(ConNone);
    enum RWL0_power_state_enum : uint8_t {
        PowerOff = 0,
        PowerOn = 1,
        PowerNoChange = 2,
        PowerAuto = 3,
        PowerOnPass = 4,
        PowerOffUpgrade = 5
    };
    inline Parameter<RWL0_power_state_enum> RWL0_power_state(PowerOff);
    inline Parameter<RWL0_power_state_enum> RWL1_power_state(PowerOff);
    inline Parameter<RWL0_power_state_enum> RWL2_power_state(PowerOff);
    inline Parameter<RWL0_power_state_enum> Mag0Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Gyro0Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Gyro1Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Fss0Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Hss0Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Str0Power(PowerOff);
    inline Parameter<int32_t> SatPosEciX(0);
    inline Parameter<int32_t> SatPosEciY(0);
    inline Parameter<int32_t> SatPosEciZ(0);
    inline Parameter<int16_t> SatVelEciX(0);
    inline Parameter<int16_t> SatVelEciY(0);
    inline Parameter<int16_t> SatVelEciZ(0);
    inline Parameter<int16_t> TgtTrackBodyVecX(0);
    inline Parameter<int16_t> TgtTrackBodyVecY(0);
    inline Parameter<int16_t> TgtTrackBodyVecZ(0);
    inline Parameter<float> TgtRefLat(0);
    inline Parameter<float> TgtRefLon(0);
    inline Parameter<float> TgtRefAlt(0);
} // namespace ADCSParameters
#pragma GCC diagnostic pop