#pragma once
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpsabi" // Suppress: parameter passing for argument of type 'Time::DefaultCUC' {aka 'TimeStamp<4, 0, 1, 10>'} changed in GCC 7.1
#include "Helpers/Parameter.hpp"
namespace OBDHParameters {
    enum ParameterID : uint16_t {
        debugCounterID = 1,
        PCBTemperature1ID = 2,
        PCBTemperature2ID = 3,
        MCUTemperatureID = 4,
        MCUInputVoltageID = 5,
        MCUSystickID = 6,
        LastFailedEventID = 7,
        MCUBootCounterID = 8,
        OperationalModeID = 9,
        SpacecraftTimeRefID = 15,
        ReconfigurationTimerID = 16,
        OnBoardTimeID = 18,
        CANBUSLoad1ID = 24,
        CANBUSLoad2ID = 25,
        CANBUSActiveID = 26,
        MCUFDIRID = 27,
        MCURestartSafeModeThresholdID = 28,
        NANDFLASHLCLThresholdID = 29,
        MRAMLCLThresholdID = 30,
        NANDFLASHONID = 31,
        MRAMONID = 32,
        FlashIntID = 33,
        SRAMIntID = 34,
        AvailableMRAMID = 35,
        AvailableNANDID = 36,
        MemoryPartitionID = 37,
        NANDFLASHScrubbingFrequencyID = 38,
        ΜRAMScrubbingFrequencyID = 39,
        ProgramFlashScrubbingFrequencyID = 40,
        CommitHashID = 44,
        CAN_ACK_timeoutID = 45,
        CAN_FrameRetransimtCountID = 46,
        CAN_TransmitFailureCountID = 47,
        UseRTTID = 48,
        UseUARTID = 49,
        UseCANID = 50,
        HeartbeatPeriodID = 51
    };
    inline Parameter<uint32_t> debugCounter(0);
    inline Parameter<float> PCBTemperature1(0);
    inline Parameter<float> PCBTemperature2(0);
    inline Parameter<float> MCUTemperature(0);
    inline Parameter<float> MCUInputVoltage(0);
    inline Parameter<uint32_t> MCUSystick(0);
    inline Parameter<uint16_t> LastFailedEvent(0);
    inline Parameter<uint16_t> MCUBootCounter(0);
    enum OperationalMode_enum : uint8_t {
        CommissioningMode = 0,
        NominalMode = 1,
        ScienceMode = 2,
        SafeMode = 3
    };
    inline Parameter<uint8_t> OperationalMode(NominalMode);
    enum SpacecraftTimeRef_enum : uint8_t {
        Spacecraft = 0,
        GroundStation = 1
    };
    inline Parameter<uint8_t> SpacecraftTimeRef(Spacecraft);
    inline Parameter<uint32_t> ReconfigurationTimer(0);
    inline Parameter<uint64_t> OnBoardTime(0);
    inline Parameter<float> CANBUSLoad1(0);
    inline Parameter<float> CANBUSLoad2(0);
    enum CANBUSActive_enum : uint8_t {
        Main = 0,
        Redundant = 1
    };
    inline Parameter<uint8_t> CANBUSActive(Main);
    enum MCUFDIR_enum : uint8_t {
        OBC = 0,
        ADCS = 1
    };
    inline Parameter<uint8_t> MCUFDIR(OBC);
    inline Parameter<uint8_t> MCURestartSafeModeThreshold(0);
    inline Parameter<float> NANDFLASHLCLThreshold(0);
    inline Parameter<float> MRAMLCLThreshold(0);
    inline Parameter<bool> NANDFLASHON(true);
    inline Parameter<bool> MRAMON(true);
    inline Parameter<uint32_t> FlashInt(0);
    inline Parameter<uint32_t> SRAMInt(0);
    inline Parameter<uint32_t> AvailableMRAM(0);
    inline Parameter<uint32_t> AvailableNAND(0);
    enum MemoryPartition_enum : uint8_t {
        First = 0,
        Second = 1
    };
    inline Parameter<uint8_t> MemoryPartition(First);
    inline Parameter<float> NANDFLASHScrubbingFrequency(0);
    inline Parameter<float> ΜRAMScrubbingFrequency(0);
    inline Parameter<float> ProgramFlashScrubbingFrequency(0);
    inline Parameter<uint16_t> CommitHash(0);
    inline Parameter<uint32_t> CAN_ACK_timeout(1000);
    inline Parameter<uint32_t> CAN_FrameRetransimtCount(0);
    inline Parameter<uint32_t> CAN_TransmitFailureCount(0);
    inline Parameter<bool> UseRTT(true);
    inline Parameter<bool> UseUART(true);
    inline Parameter<bool> UseCAN(false);
    inline Parameter<uint32_t> HeartbeatPeriod(3000);
} // namespace OBDHParameters
namespace COMMSParameters {
    enum ParameterID : uint16_t {
        uhf_power_amp_tempID = 820,
        pcb_tempID = 821,
        gnss_tempID = 822,
        antenna_deployment_statusID = 824,
        cw_intervalID = 827,
        bfsk_beacon_intervalID = 828,
        uhf_tx_powerID = 829,
        rssiID = 834,
        gnss_latID = 850,
        gnss_longID = 851,
        gnss_altID = 852,
        gnss_timeID = 853,
        gnss_ack_timeoutID = 854,
        gnss_cmd_retriesID = 855,
        gnss_error_timeoutID = 856,
        error_timeout_cnt_thrhdID = 857,
        gnss_delay_cmdsID = 858,
        satellites_trackedID = 859,
        gnss_fix_qualityID = 860,
        gnss_TM_data_periodID = 861,
        commit_hashID = 862,
        emmc_usageID = 905
    };
    inline Parameter<float> uhf_power_amp_temp(0);
    inline Parameter<float> pcb_temp(0);
    inline Parameter<float> gnss_temp(0);
    enum antenna_deployment_status_enum : uint8_t {
        Closed = 0,
        OneDoorOpen = 1,
        TwoDoorOpen = 2,
        ThreeDoorOpen = 3,
        FullyDeployed = 4
    };
    inline Parameter<uint8_t> antenna_deployment_status(Closed);
    inline Parameter<uint16_t> cw_interval(0);
    inline Parameter<uint16_t> bfsk_beacon_interval(0);
    inline Parameter<uint32_t> uhf_tx_power(0);
    inline Parameter<float> rssi(0);
    inline Parameter<int32_t> gnss_lat(0);
    inline Parameter<int32_t> gnss_long(0);
    inline Parameter<int32_t> gnss_alt(0);
    inline Parameter<float> gnss_time(0);
    inline Parameter<uint16_t> gnss_ack_timeout(0);
    inline Parameter<uint8_t> gnss_cmd_retries(0);
    inline Parameter<uint16_t> gnss_error_timeout(0);
    inline Parameter<uint16_t> error_timeout_cnt_thrhd(0);
    inline Parameter<uint16_t> gnss_delay_cmds(0);
    inline Parameter<int8_t> satellites_tracked(0);
    inline Parameter<int8_t> gnss_fix_quality(0);
    inline Parameter<uint8_t> gnss_TM_data_period(10);
    inline Parameter<uint16_t> commit_hash(0);
    inline Parameter<float> emmc_usage(0);
} // namespace COMMSParameters
namespace PAYParameters {
    enum ParameterID : uint16_t {
        pointing_offset_xID = 1639,
        pointing_offset_yID = 1640,
        pointing_offset_zID = 1641,
        uptimeID = 1642,
        timeID = 1643,
        psu_12vID = 1644,
        psu_5vID = 1645,
        psu_33vID = 1646,
        mcu_die_temperatureID = 1647,
        main_board_temperatureID = 1648,
        seed_ld_output_powerID = 1649,
        fsm_chamber_temperatureID = 1650,
        fsm_chamber_pressureID = 1651,
        fsmd_voltage_converter_temperatureID = 1652,
        fsmd_drivers_temperatureID = 1653,
        camera_pcb_temperatureID = 1654,
        camera_sensor_temperatureID = 1655,
        fso_aux_temperature_1ID = 1656,
        fso_aux_temperature_2ID = 1657,
        oad_temperatureID = 1658,
        optical_amplifier_combiner_heater_temperatureID = 1659,
        optical_amplifier_fiber_mirror_temperatureID = 1660,
        optical_amplifier_circulator_heater_temperatureID = 1661,
        ldd_temperatureID = 1662,
        ld_temperatureID = 1663,
        ldd_12v_currentID = 1664,
        ldd_psu_12vID = 1665,
        ldd_converter_input_currentID = 1666,
        ldd_ld_vID = 1667,
        ldd_ld_dac_set_vID = 1668,
        fsm_driver_12v_currentID = 1669,
        flashes_33v_currentID = 1670,
        fpga_5v_currentID = 1671,
        sdd_33v_currentID = 1672,
        pump_ld_powerID = 1673,
        mcu_33v_currentID = 1674,
        fpga_die_temperatureID = 1675,
        fpga_vdd1_voltageID = 1676,
        fpga_vdd18_voltageID = 1677,
        fpga_vdd25_voltageID = 1678,
        seed_ld_incoming_powerID = 1679,
        amplifier_output_powerID = 1680,
        amplifier_output_reflected_powerID = 1681,
        seed_diode_bias_currentID = 1682,
        tec_currentID = 1683,
        ldd_output_currentID = 1684,
        sd_temperature_violationsID = 1685,
        end_uptimeID = 1686,
        responseID = 1687,
        deviceID = 1688,
        firmwareID = 1689,
        firmware_is_confirmedID = 1690,
        bitstreamID = 1691,
        softcpu_1_firmwareID = 1692,
        softcpu_2_firmwareID = 1693,
        softcpu_3_firmwareID = 1694,
        softcpu_4_firmwareID = 1695,
        softcpu_5_firmwareID = 1696,
        softcpu_6_firmwareID = 1697,
        softcpu_7_firmwareID = 1698,
        softcpu_8_firmwareID = 1699,
        boot_countID = 1700,
        transmission_countID = 1701,
        hw_detID = 1702,
        storage0ID = 1703,
        storage1ID = 1704,
        storage2ID = 1705,
        storage3ID = 1706,
        ldd_faultID = 1707,
        fsm_faultID = 1708,
        fpga_faultID = 1709,
        v_cam_faultID = 1711,
        sdd_faultID = 1712
    };
    inline Parameter<int32_t> pointing_offset_x(0);
    inline Parameter<int32_t> pointing_offset_y(0);
    inline Parameter<int32_t> pointing_offset_z(0);
    inline Parameter<int32_t> uptime(0);
    inline Parameter<int32_t> time(0);
    inline Parameter<int32_t> psu_12v(0);
    inline Parameter<int32_t> psu_5v(0);
    inline Parameter<int32_t> psu_33v(0);
    inline Parameter<int32_t> mcu_die_temperature(0);
    inline Parameter<int32_t> main_board_temperature(0);
    inline Parameter<int32_t> seed_ld_output_power(0);
    inline Parameter<int32_t> fsm_chamber_temperature(0);
    inline Parameter<int32_t> fsm_chamber_pressure(0);
    inline Parameter<int32_t> fsmd_voltage_converter_temperature(0);
    inline Parameter<int32_t> fsmd_drivers_temperature(0);
    inline Parameter<int32_t> camera_pcb_temperature(0);
    inline Parameter<int32_t> camera_sensor_temperature(0);
    inline Parameter<int32_t> fso_aux_temperature_1(0);
    inline Parameter<int32_t> fso_aux_temperature_2(0);
    inline Parameter<int32_t> oad_temperature(0);
    inline Parameter<int32_t> optical_amplifier_combiner_heater_temperature(0);
    inline Parameter<int32_t> optical_amplifier_fiber_mirror_temperature(0);
    inline Parameter<int32_t> optical_amplifier_circulator_heater_temperature(0);
    inline Parameter<int32_t> ldd_temperature(0);
    inline Parameter<int32_t> ld_temperature(0);
    inline Parameter<int32_t> ldd_12v_current(0);
    inline Parameter<int32_t> ldd_psu_12v(0);
    inline Parameter<int32_t> ldd_converter_input_current(0);
    inline Parameter<int32_t> ldd_ld_v(0);
    inline Parameter<int32_t> ldd_ld_dac_set_v(0);
    inline Parameter<int32_t> fsm_driver_12v_current(0);
    inline Parameter<int32_t> flashes_33v_current(0);
    inline Parameter<int32_t> fpga_5v_current(0);
    inline Parameter<int32_t> sdd_33v_current(0);
    inline Parameter<int32_t> pump_ld_power(0);
    inline Parameter<int32_t> mcu_33v_current(0);
    inline Parameter<int32_t> fpga_die_temperature(0);
    inline Parameter<int32_t> fpga_vdd1_voltage(0);
    inline Parameter<int32_t> fpga_vdd18_voltage(0);
    inline Parameter<int32_t> fpga_vdd25_voltage(0);
    inline Parameter<int32_t> seed_ld_incoming_power(0);
    inline Parameter<int32_t> amplifier_output_power(0);
    inline Parameter<int32_t> amplifier_output_reflected_power(0);
    inline Parameter<int32_t> seed_diode_bias_current(0);
    inline Parameter<int32_t> tec_current(0);
    inline Parameter<int32_t> ldd_output_current(0);
    inline Parameter<int32_t> sd_temperature_violations(0);
    inline Parameter<int32_t> end_uptime(0);
    inline Parameter<int32_t> response(0);
    inline Parameter<int32_t> device(0);
    inline Parameter<int32_t> firmware(0);
    inline Parameter<int32_t> firmware_is_confirmed(0);
    inline Parameter<int32_t> bitstream(0);
    inline Parameter<int32_t> softcpu_1_firmware(0);
    inline Parameter<int32_t> softcpu_2_firmware(0);
    inline Parameter<int32_t> softcpu_3_firmware(0);
    inline Parameter<int32_t> softcpu_4_firmware(0);
    inline Parameter<int32_t> softcpu_5_firmware(0);
    inline Parameter<int32_t> softcpu_6_firmware(0);
    inline Parameter<int32_t> softcpu_7_firmware(0);
    inline Parameter<int32_t> softcpu_8_firmware(0);
    inline Parameter<int32_t> boot_count(0);
    inline Parameter<int32_t> transmission_count(0);
    inline Parameter<int32_t> hw_det(0);
    inline Parameter<int32_t> storage0(0);
    inline Parameter<int32_t> storage1(0);
    inline Parameter<int32_t> storage2(0);
    inline Parameter<int32_t> storage3(0);
    inline Parameter<int32_t> ldd_fault(0);
    inline Parameter<int32_t> fsm_fault(0);
    inline Parameter<int32_t> fpga_fault(0);
    inline Parameter<int32_t> v_cam_fault(0);
    inline Parameter<int32_t> sdd_fault(0);
} // namespace PAYParameters
namespace ADCSParameters {
    enum ParameterID : uint16_t {
        ResetTypeID = 2458,
        UnixTimeSecondsID = 2459,
        UnixTimeNanoSecondsID = 2460,
        AdcsRunModeSelectID = 2461,
        RunModeDefaultID = 2462,
        OpStateDefaultID = 2463,
        OpStateID = 2464,
        IxxID = 2465,
        IyyID = 2466,
        IzzID = 2467,
        IxyID = 2468,
        IxzID = 2469,
        IyzID = 2470,
        RWL0_power_stateID = 2471,
        RWL1_power_stateID = 2472,
        RWL2_power_stateID = 2473,
        Mag0PowerID = 2474,
        Gyro0PowerID = 2475,
        Gyro1PowerID = 2476,
        Fss0PowerID = 2477,
        Hss0PowerID = 2478,
        Str0PowerID = 2479,
        RwlFailIdID = 2480,
        MountStackXID = 2481,
        MountStackYID = 2482,
        MountStackZID = 2483,
        MountMtq0ID = 2484,
        MountMtq1ID = 2485,
        MountMtq2ID = 2486,
        MountRwl0ID = 2487,
        MountRwl1ID = 2488,
        MountRwl2ID = 2489,
        MountFss0AlphaID = 2490,
        MountFss0BetaID = 2491,
        MountFss0GammaID = 2492,
        MountHss0AlphaID = 2493,
        MountHss0BetaID = 2494,
        MountHss0GammaID = 2495,
        MountMag0AlphaID = 2496,
        MountMag0BetaID = 2497,
        MountMag0GammaID = 2498,
        MountMag1AlphaID = 2499,
        MountMag1BetaID = 2500,
        MountMag1GammaID = 2501,
        MountStr0AlphaID = 2502,
        MountStr0BetaID = 2503,
        MountStr0GammaID = 2504,
        EstModeMainDefaultID = 2507,
        EstModeBackupDefaultID = 2508,
        EstModeMainID = 2509,
        EstModeBackupID = 2510,
        EkfUseFssID = 2511,
        EkfUseCssID = 2512,
        EkfUseHssID = 2513,
        EkfUseStrID = 2514,
        EstRpyRollID = 2515,
        EstRpyPitchID = 2516,
        EstRpyYawID = 2517,
        EstRateIrcXID = 2518,
        EstRateIrcYID = 2519,
        EstRateIrcZID = 2520,
        EstStdDevQ0ID = 2521,
        EstStdDevQ1ID = 2522,
        EstStdDevQ2ID = 2523,
        EstStdDevRateXID = 2524,
        EstStdDevRateYID = 2525,
        EstStdDevRateZID = 2526,
        Str0Quat1ID = 2527,
        Str0Quat2ID = 2528,
        Str0Quat3ID = 2529,
        Str0Quat4ID = 2530,
        Str0AngVelXID = 2531,
        Str0AngVelYID = 2532,
        Str0AngVelZID = 2533,
        OrbModeID = 2534,
        BatchSizeID = 2535,
        MaxTimeBetweenID = 2536,
        MaxPosErrID = 2537,
        TimeGainID = 2538,
        UpdateRaanInclID = 2539,
        UpdateEccenID = 2540,
        UpdateApMaID = 2541,
        UpdateTimeID = 2542,
        OrbitEpochID = 2543,
        OrbitInclID = 2544,
        OrbitRaanID = 2545,
        OrbitEccenID = 2546,
        OrbitAPID = 2547,
        OrbitMAID = 2548,
        OrbitMMID = 2549,
        OrbitBstarID = 2550,
        GnssTimeSecondsID = 2551,
        GnssTimeNsID = 2552,
        GnssSatPosXID = 2553,
        GnssSatPosYID = 2554,
        GnssSatPosZID = 2555,
        SyncTimeID = 2556,
        SatPosEciXID = 2557,
        SatPosEciYID = 2558,
        SatPosEciZID = 2559,
        SatVelEciXID = 2560,
        SatVelEciYID = 2561,
        SatVelEciZID = 2562,
        ConModeSelectID = 2563,
        ConModeDefaultID = 2564,
        ConModeSafeID = 2565,
        ConModeAutoID = 2566,
        SunKeepoutAngID = 2567,
        SunAvoidEnID = 2568,
        RpyCmdRollID = 2569,
        RpyCmdPitchID = 2570,
        RpyCmdYawID = 2571,
        Mtq0OnTimeCmdID = 2572,
        Mtq1OnTimeCmdID = 2573,
        Mtq2OnTimeCmdID = 2574,
        Rwl0SpeedCmdID = 2575,
        Rwl1SpeedCmdID = 2576,
        Rwl2SpeedCmdID = 2577,
        TgtTrackBodyVecXID = 2578,
        TgtTrackBodyVecYID = 2579,
        TgtTrackBodyVecZID = 2580,
        TgtRefLatID = 2581,
        TgtRefLonID = 2582,
        TgtRefAltID = 2583,
        SunPointBodyVecXID = 2584,
        SunPointBodyVecYID = 2585,
        SunPointBodyVecZID = 2586,
        ModelMagOrcXID = 2587,
        ModelMagOrcYID = 2588,
        ModelMagOrcZID = 2589,
        ModelSunOrcXID = 2590,
        ModelSunOrcYID = 2591,
        ModelSunOrcZID = 2592
    };
    enum ResetType_enum : uint8_t {
        DoNothng = 0,
        Soft = 55,
        Hard = 66
    };
    inline Parameter<uint8_t> ResetType(DoNothng);
    inline Parameter<uint32_t> UnixTimeSeconds(0);
    inline Parameter<uint32_t> UnixTimeNanoSeconds(0);
    enum AdcsRunModeSelect_enum : uint8_t {
        AdcsOff = 0,
        AdcsEnabled = 1,
        AdcsTriggered = 2,
        AdcsSimulation = 3
    };
    inline Parameter<uint8_t> AdcsRunModeSelect(AdcsOff);
    inline Parameter<AdcsRunModeSelect_enum> RunModeDefault(AdcsOff);
    enum OpStateDefault_enum : uint8_t {
        OpStateManual = 0,
        OpStateAuto = 1,
        OpStateSafe = 2,
        OpStateFault = 3
    };
    inline Parameter<uint8_t> OpStateDefault(OpStateManual);
    inline Parameter<OpStateDefault_enum> OpState(OpStateSafe);
    inline Parameter<float> Ixx(0);
    inline Parameter<float> Iyy(0);
    inline Parameter<float> Izz(0);
    inline Parameter<float> Ixy(0);
    inline Parameter<float> Ixz(0);
    inline Parameter<float> Iyz(0);
    enum RWL0_power_state_enum : uint16_t {
        PowerOff = 0,
        PowerOn = 1,
        PowerNoChange = 2,
        PowerAuto = 3,
        PowerOnPass = 4,
        PowerOffUpgrade = 5
    };
    inline Parameter<uint16_t> RWL0_power_state(PowerOff);
    inline Parameter<RWL0_power_state_enum> RWL1_power_state(PowerOff);
    inline Parameter<RWL0_power_state_enum> RWL2_power_state(PowerOff);
    inline Parameter<RWL0_power_state_enum> Mag0Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Gyro0Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Gyro1Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Fss0Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Hss0Power(PowerOff);
    inline Parameter<RWL0_power_state_enum> Str0Power(PowerOff);
    enum RwlFailId_enum : uint8_t {
        RwlFailNone = 0,
        RwlFail0 = 1,
        RwlFail1 = 2,
        RwlFail2 = 3,
        RwlFail3 = 4
    };
    inline Parameter<uint8_t> RwlFailId(RwlFailNone);
    enum MountStackX_enum : uint8_t {
        AxisNotUsed = 0,
        AxisPosX = 1,
        AxisNegX = 2,
        AxisPosY = 3,
        AxisNegY = 4,
        AxisPosZ = 5,
        AxisNegZ = 6,
        AxisThdA = 7,
        AxisThdB = 8,
        AxisThdC = 9,
        AxisThdD = 10,
        AxisPmdA = 11,
        AxisPmdB = 12,
        AxisPmdC = 13,
        AxisPmdD = 14,
        AxisSkew = 15
    };
    inline Parameter<uint8_t> MountStackX(AxisNegY);
    inline Parameter<MountStackX_enum> MountStackY(AxisNegX);
    inline Parameter<MountStackX_enum> MountStackZ(AxisNegZ);
    inline Parameter<MountStackX_enum> MountMtq0(AxisNegY);
    inline Parameter<MountStackX_enum> MountMtq1(AxisNegX);
    inline Parameter<MountStackX_enum> MountMtq2(AxisNegZ);
    inline Parameter<MountStackX_enum> MountRwl0(AxisNegY);
    inline Parameter<MountStackX_enum> MountRwl1(AxisNegX);
    inline Parameter<MountStackX_enum> MountRwl2(AxisNegZ);
    inline Parameter<int16_t> MountFss0Alpha(0);
    inline Parameter<int16_t> MountFss0Beta(0);
    inline Parameter<int16_t> MountFss0Gamma(0);
    inline Parameter<int16_t> MountHss0Alpha(0);
    inline Parameter<int16_t> MountHss0Beta(0);
    inline Parameter<int16_t> MountHss0Gamma(0);
    inline Parameter<int16_t> MountMag0Alpha(0);
    inline Parameter<int16_t> MountMag0Beta(0);
    inline Parameter<int16_t> MountMag0Gamma(0);
    inline Parameter<int16_t> MountMag1Alpha(0);
    inline Parameter<int16_t> MountMag1Beta(0);
    inline Parameter<int16_t> MountMag1Gamma(0);
    inline Parameter<int16_t> MountStr0Alpha(0);
    inline Parameter<int16_t> MountStr0Beta(0);
    inline Parameter<int16_t> MountStr0Gamma(0);
    enum EstModeMainDefault_enum : uint8_t {
        EstNone = 0,
        EstGyro = 1,
        EstMagRkf = 2,
        EstPitchRkf = 3,
        EstTriad = 4,
        EstFullEkf = 5,
        EstGyroEkf = 6,
        EstUser = 100
    };
    inline Parameter<uint8_t> EstModeMainDefault(EstGyro);
    inline Parameter<EstModeMainDefault_enum> EstModeBackupDefault(EstGyro);
    inline Parameter<EstModeMainDefault_enum> EstModeMain(EstGyro);
    inline Parameter<EstModeMainDefault_enum> EstModeBackup(EstGyro);
    inline Parameter<bool> EkfUseFss(0);
    inline Parameter<bool> EkfUseCss(0);
    inline Parameter<bool> EkfUseHss(0);
    inline Parameter<bool> EkfUseStr(0);
    inline Parameter<int16_t> EstRpyRoll(0);
    inline Parameter<int16_t> EstRpyPitch(0);
    inline Parameter<int16_t> EstRpyYaw(0);
    inline Parameter<int16_t> EstRateIrcX(0);
    inline Parameter<int16_t> EstRateIrcY(0);
    inline Parameter<int16_t> EstRateIrcZ(0);
    inline Parameter<int16_t> EstStdDevQ0(0);
    inline Parameter<int16_t> EstStdDevQ1(0);
    inline Parameter<int16_t> EstStdDevQ2(0);
    inline Parameter<int16_t> EstStdDevRateX(0);
    inline Parameter<int16_t> EstStdDevRateY(0);
    inline Parameter<int16_t> EstStdDevRateZ(0);
    inline Parameter<float> Str0Quat1(0);
    inline Parameter<float> Str0Quat2(0);
    inline Parameter<float> Str0Quat3(0);
    inline Parameter<float> Str0Quat4(0);
    inline Parameter<uint16_t> Str0AngVelX(0);
    inline Parameter<uint16_t> Str0AngVelY(0);
    inline Parameter<uint16_t> Str0AngVelZ(0);
    enum OrbMode_enum : uint8_t {
        OrbTle = 0,
        OrbTleGnss = 1,
        OrbAsgp4 = 2,
        OrbAsgp4Gnss = 3
    };
    inline Parameter<uint8_t> OrbMode(OrbTle);
    inline Parameter<uint16_t> BatchSize(0);
    inline Parameter<uint32_t> MaxTimeBetween(0);
    inline Parameter<uint16_t> MaxPosErr(0);
    inline Parameter<float> TimeGain(0);
    inline Parameter<bool> UpdateRaanIncl(0);
    inline Parameter<bool> UpdateEccen(0);
    inline Parameter<bool> UpdateApMa(0);
    inline Parameter<bool> UpdateTime(0);
    inline Parameter<double> OrbitEpoch(0);
    inline Parameter<double> OrbitIncl(0);
    inline Parameter<double> OrbitRaan(0);
    inline Parameter<double> OrbitEccen(0);
    inline Parameter<double> OrbitAP(0);
    inline Parameter<double> OrbitMA(0);
    inline Parameter<double> OrbitMM(0);
    inline Parameter<double> OrbitBstar(0);
    inline Parameter<uint32_t> GnssTimeSeconds(0);
    inline Parameter<uint32_t> GnssTimeNs(0);
    inline Parameter<int32_t> GnssSatPosX(0);
    inline Parameter<int32_t> GnssSatPosY(0);
    inline Parameter<int32_t> GnssSatPosZ(0);
    inline Parameter<bool> SyncTime(0);
    inline Parameter<int32_t> SatPosEciX(0);
    inline Parameter<int32_t> SatPosEciY(0);
    inline Parameter<int32_t> SatPosEciZ(0);
    inline Parameter<int16_t> SatVelEciX(0);
    inline Parameter<int16_t> SatVelEciY(0);
    inline Parameter<int16_t> SatVelEciZ(0);
    enum ConModeSelect_enum : uint8_t {
        ConNone = 0,
        ConBdot = 1,
        ConYspin = 2,
        ConBdot3 = 3,
        ConDetumble = 4,
        ConSunYspin = 5,
        ConZspin = 6,
        ConSunZspin = 7,
        ConGGboom = 8,
        ConGGsun = 9,
        ConYwheelInit = 10,
        ConYwheel = 11,
        ConXYZwheel = 12,
        ConSunTrack = 13,
        ConTgtTrack = 14,
        ConTgtSteer = 15,
        ConGndTrack = 16,
        ConIrcTrack = 17,
        ConMoonTrack = 18,
        ConSatTrack = 19,
        ConYawSun = 20,
        ConYawTarget = 21,
        ConRollSun = 22,
        ConRollTarget = 23,
        ConYawTargetBest = 24,
        ConFmcTarget = 25,
        ConYawSunSpin = 26,
        ConSunDetumble = 27,
        ConAstroSteer = 28,
        ConSunPayload = 29,
        ConStopRW = 50,
        ConHxyzRW = 51,
        ConUser = 100
    };
    inline Parameter<uint8_t> ConModeSelect(ConNone);
    inline Parameter<ConModeSelect_enum> ConModeDefault(ConNone);
    inline Parameter<ConModeSelect_enum> ConModeSafe(ConNone);
    inline Parameter<ConModeSelect_enum> ConModeAuto(ConNone);
    inline Parameter<float> SunKeepoutAng(0);
    inline Parameter<bool> SunAvoidEn(0);
    inline Parameter<int16_t> RpyCmdRoll(0);
    inline Parameter<int16_t> RpyCmdPitch(0);
    inline Parameter<int16_t> RpyCmdYaw(0);
    inline Parameter<int16_t> Mtq0OnTimeCmd(0);
    inline Parameter<int16_t> Mtq1OnTimeCmd(0);
    inline Parameter<int16_t> Mtq2OnTimeCmd(0);
    inline Parameter<float> Rwl0SpeedCmd(0);
    inline Parameter<float> Rwl1SpeedCmd(0);
    inline Parameter<float> Rwl2SpeedCmd(0);
    inline Parameter<int16_t> TgtTrackBodyVecX(0);
    inline Parameter<int16_t> TgtTrackBodyVecY(0);
    inline Parameter<int16_t> TgtTrackBodyVecZ(0);
    inline Parameter<float> TgtRefLat(0);
    inline Parameter<float> TgtRefLon(0);
    inline Parameter<float> TgtRefAlt(0);
    inline Parameter<int16_t> SunPointBodyVecX(0);
    inline Parameter<int16_t> SunPointBodyVecY(0);
    inline Parameter<int16_t> SunPointBodyVecZ(0);
    inline Parameter<int16_t> ModelMagOrcX(0);
    inline Parameter<int16_t> ModelMagOrcY(0);
    inline Parameter<int16_t> ModelMagOrcZ(0);
    inline Parameter<int16_t> ModelSunOrcX(0);
    inline Parameter<int16_t> ModelSunOrcY(0);
    inline Parameter<int16_t> ModelSunOrcZ(0);
} // namespace ADCSParameters
namespace EPSParameters {
    enum ParameterID : uint16_t {
        EPS_MODEID = 3277,
        EPS_CONFID = 3278,
        EPS_RESET_CAUSEID = 3279,
        EPS_UPTIMEID = 3280,
        EPS_ERRORID = 3281,
        EPS_RC_CNT_PWRONID = 3282,
        EPS_RC_CNT_WDGID = 3283,
        EPS_RC_CNT_CMDID = 3284,
        EPS_RC_CNT_MCUID = 3285,
        EPS_RC_CNT_EMLOPOID = 3286,
        EPS_PREVCMD_ELAPSEDID = 3287,
        EPS_UNIX_TIMEID = 3288,
        EPS_UNIX_YEARID = 3289,
        EPS_UNIX_MONTHID = 3290,
        EPS_UNIX_DAYID = 3291,
        EPS_UNIX_HOURID = 3292,
        EPS_UNIX_MINUTEID = 3293,
        EPS_UNIX_SECONDID = 3294,
        EPS_STAT_CH_ONID = 3295,
        EPS_STAT_CH_EXT_ONID = 3296,
        EPS_STAT_CH_OCFID = 3297,
        EPS_STAT_CH_EXT_OCFID = 3298,
        EPS_OCF_CNT_CH00ID = 3299,
        EPS_OCF_CNT_CH01ID = 3300,
        EPS_OCF_CNT_CH02ID = 3301,
        EPS_OCF_CNT_CH03ID = 3302,
        EPS_OCF_CNT_CH04ID = 3303,
        EPS_OCF_CNT_CH05ID = 3304,
        EPS_OCF_CNT_CH06ID = 3305,
        EPS_OCF_CNT_CH07ID = 3306,
        EPS_OCF_CNT_CH08ID = 3307,
        EPS_OCF_CNT_CH09ID = 3308,
        EPS_OCF_CNT_CH10ID = 3309,
        EPS_OCF_CNT_CH11ID = 3310,
        EPS_OCF_CNT_CH12ID = 3311,
        EPS_OCF_CNT_CH13ID = 3312,
        EPS_OCF_CNT_CH14ID = 3313,
        EPS_OCF_CNT_CH15ID = 3314,
        EPS_ABF_PLACED_0ID = 3316,
        EPS_ABF_PLACED_1ID = 3317,
        EPS_VOLT_BRDSUP_RAWID = 3318,
        EPS_TEMP_MCU_RAWID = 3319,
        EPS_VIP_VOLT_VD0_RAWID = 3320,
        EPS_VIP_VOLT_VD1_RAWID = 3321,
        EPS_VIP_VOLT_VD2_RAWID = 3322,
        EPS_VIP_VOLT_VD3_RAWID = 3323,
        EPS_VIP_VOLT_VD4_RAWID = 3324,
        EPS_VIP_VOLT_VD5_RAWID = 3325,
        EPS_VIP_VOLT_VD6_RAWID = 3326,
        EPS_VIP_CURR_VD0_RAWID = 3327,
        EPS_VIP_CURR_VD1_RAWID = 3328,
        EPS_VIP_CURR_VD2_RAWID = 3329,
        EPS_VIP_CURR_VD3_RAWID = 3330,
        EPS_VIP_CURR_VD4_RAWID = 3331,
        EPS_VIP_CURR_VD5_RAWID = 3332,
        EPS_VIP_CURR_VD6_RAWID = 3333,
        EPS_VIP_POWE_VD0_RAWID = 3334,
        EPS_VIP_POWE_VD1_RAWID = 3335,
        EPS_VIP_POWE_VD2_RAWID = 3336,
        EPS_VIP_POWE_VD3_RAWID = 3337,
        EPS_VIP_POWE_VD4_RAWID = 3338,
        EPS_VIP_POWE_VD5_RAWID = 3339,
        EPS_VIP_POWE_VD6_RAWID = 3340,
        EPS_VOLT_BRDSUP_ENGID = 3341,
        EPS_TEMP_MCU_ENGID = 3342,
        EPS_VIP_VOLT_INPUT_ENGID = 3343,
        EPS_VIP_CURR_INPUT_ENGID = 3344,
        EPS_VIP_POWE_INPUT_ENGID = 3345,
        EPS_VIP_VOLT_DIST_INPUT_ENGID = 3346,
        EPS_VIP_CURR_DIST_INPUT_ENGID = 3347,
        EPS_VIP_POWE_DIST_INPUT_ENGID = 3348,
        EPS_VIP_VOLT_BAT_INPUT_ENGID = 3349,
        EPS_VIP_CURR_BAT_INPUT_ENGID = 3350,
        EPS_VIP_POWE_BAT_INPUT_ENGID = 3351,
        EPS_VIP_VOLT_VD0_ENGID = 3352,
        EPS_VIP_CURR_VD0_ENGID = 3353,
        EPS_VIP_POWE_VD0_ENGID = 3354,
        EPS_VIP_VOLT_VD1_ENGID = 3355,
        EPS_VIP_CURR_VD1_ENGID = 3356,
        EPS_VIP_POWE_VD1_ENGID = 3357,
        EPS_VIP_VOLT_VD2_ENGID = 3358,
        EPS_VIP_CURR_VD2_ENGID = 3359,
        EPS_VIP_POWE_VD2_ENGID = 3360,
        EPS_VIP_VOLT_VD3_ENGID = 3361,
        EPS_VIP_CURR_VD3_ENGID = 3362,
        EPS_VIP_POWE_VD3_ENGID = 3363,
        EPS_VIP_VOLT_VD4_ENGID = 3364,
        EPS_VIP_CURR_VD4_ENGID = 3365,
        EPS_VIP_POWE_VD4_ENGID = 3366,
        EPS_VIP_VOLT_VD5_ENGID = 3367,
        EPS_VIP_CURR_VD5_ENGID = 3368,
        EPS_VIP_POWE_VD5_ENGID = 3369,
        EPS_VIP_VOLT_VD6_ENGID = 3370,
        EPS_VIP_POWE_VD6_ENGID = 3371,
        EPS_VIP_CH00_VOLT_RAWID = 3372,
        EPS_VIP_CH00_CURR_RAWID = 3373,
        EPS_VIP_CH00_POWE_RAWID = 3374,
        EPS_VIP_CH01_VOLT_RAWID = 3375,
        EPS_VIP_CH01_CURR_RAWID = 3376,
        EPS_VIP_CH01_POWE_RAWID = 3377,
        EPS_VIP_CH02_VOLT_RAWID = 3378,
        EPS_VIP_CH02_CURR_RAWID = 3379,
        EPS_VIP_CH02_POWE_RAWID = 3380,
        EPS_VIP_CH03_VOLT_RAWID = 3381,
        EPS_VIP_CH03_CURR_RAWID = 3382,
        EPS_VIP_CH03_POWE_RAWID = 3383,
        EPS_VIP_CH04_VOLT_RAWID = 3384,
        EPS_VIP_CH04_CURR_RAWID = 3385,
        EPS_VIP_CH04_POWE_RAWID = 3386,
        EPS_VIP_CH05_VOLT_RAWID = 3387,
        EPS_VIP_CH05_CURR_RAWID = 3388,
        EPS_VIP_CH05_POWE_RAWID = 3389,
        EPS_VIP_CH06_VOLT_RAWID = 3390,
        EPS_VIP_CH06_CURR_RAWID = 3391,
        EPS_VIP_CH06_POWE_RAWID = 3392,
        EPS_VIP_CH07_VOLT_RAWID = 3393,
        EPS_VIP_CH07_CURR_RAWID = 3394,
        EPS_VIP_CH07_POWE_RAWID = 3395,
        EPS_VIP_CH08_VOLT_RAWID = 3396,
        EPS_VIP_CH08_CURR_RAWID = 3397,
        EPS_VIP_CH08_POWE_RAWID = 3398,
        EPS_VIP_CH09_VOLT_RAWID = 3399,
        EPS_VIP_CH09_CURR_RAWID = 3400,
        EPS_VIP_CH09_POWE_RAWID = 3401,
        EPS_VIP_CH10_VOLT_RAWID = 3402,
        EPS_VIP_CH10_CURR_RAWID = 3403,
        EPS_VIP_CH10_POWE_RAWID = 3404,
        EPS_VIP_CH11_VOLT_RAWID = 3405,
        EPS_VIP_CH11_CURR_RAWID = 3406,
        EPS_VIP_CH11_POWE_RAWID = 3407,
        EPS_VIP_CH12_VOLT_RAWID = 3408,
        EPS_VIP_CH12_CURR_RAWID = 3409,
        EPS_VIP_CH12_POWE_RAWID = 3410,
        EPS_VIP_CH13_VOLT_RAWID = 3411,
        EPS_VIP_CH13_CURR_RAWID = 3412,
        EPS_VIP_CH13_POWE_RAWID = 3413,
        EPS_VIP_CH14_VOLT_RAWID = 3414,
        EPS_VIP_CH14_CURR_RAWID = 3415,
        EPS_VIP_CH14_POWE_RAWID = 3416,
        EPS_VIP_CH00_VOLT_ENGID = 3417,
        EPS_VIP_CH00_CURR_ENGID = 3418,
        EPS_VIP_CH00_POWE_ENGID = 3419,
        EPS_VIP_CH01_VOLT_ENGID = 3420,
        EPS_VIP_CH01_CURR_ENGID = 3421,
        EPS_VIP_CH01_POWE_ENGID = 3422,
        EPS_VIP_CH02_VOLT_ENGID = 3423,
        EPS_VIP_CH02_CURR_ENGID = 3424,
        EPS_VIP_CH02_POWE_ENGID = 3425,
        EPS_VIP_CH03_VOLT_ENGID = 3426,
        EPS_VIP_CH03_CURR_ENGID = 3427,
        EPS_VIP_CH03_POWE_ENGID = 3428,
        EPS_VIP_CH04_VOLT_ENGID = 3429,
        EPS_VIP_CH04_CURR_ENGID = 3430,
        EPS_VIP_CH04_POWE_ENGID = 3431,
        EPS_VIP_CH05_VOLT_ENGID = 3432,
        EPS_VIP_CH05_CURR_ENGID = 3433,
        EPS_VIP_CH05_POWE_ENGID = 3434,
        EPS_VIP_CH06_VOLT_ENGID = 3435,
        EPS_VIP_CH06_CURR_ENGID = 3436,
        EPS_VIP_CH06_POWE_ENGID = 3437,
        EPS_VIP_CH07_VOLT_ENGID = 3438,
        EPS_VIP_CH07_CURR_ENGID = 3439,
        EPS_VIP_CH07_POWE_ENGID = 3440,
        EPS_VIP_CH08_VOLT_ENGID = 3441,
        EPS_VIP_CH08_CURR_ENGID = 3442,
        EPS_VIP_CH08_POWE_ENGID = 3443,
        EPS_VIP_CH09_VOLT_ENGID = 3444,
        EPS_VIP_CH09_CURR_ENGID = 3445,
        EPS_VIP_CH09_POWE_ENGID = 3446,
        EPS_VIP_CH10_VOLT_ENGID = 3447,
        EPS_VIP_CH10_CURR_ENGID = 3448,
        EPS_VIP_CH10_POWE_ENGID = 3449,
        EPS_VIP_CH11_VOLT_ENGID = 3450,
        EPS_VIP_CH11_CURR_ENGID = 3451,
        EPS_VIP_CH11_POWE_ENGID = 3452,
        EPS_VIP_CH12_VOLT_ENGID = 3453,
        EPS_VIP_CH12_CURR_ENGID = 3454,
        EPS_VIP_CH12_POWE_ENGID = 3455,
        EPS_VIP_CH13_VOLT_ENGID = 3456,
        EPS_VIP_CH13_CURR_ENGID = 3457,
        EPS_VIP_CH13_POWE_ENGID = 3458,
        EPS_VIP_CH14_VOLT_ENGID = 3459,
        EPS_VIP_CH14_CURR_ENGID = 3460,
        EPS_VIP_CH14_POWE_ENGID = 3461,
        EPS_VIP_CH00_VOLT_RAID = 3462,
        EPS_VIP_CH00_CURR_RAID = 3463,
        EPS_VIP_CH00_POWE_RAID = 3464,
        EPS_VIP_CH01_VOLT_RAID = 3465,
        EPS_VIP_CH01_CURR_RAID = 3466,
        EPS_VIP_CH01_POWE_RAID = 3467,
        EPS_VIP_CH02_VOLT_RAID = 3468,
        EPS_VIP_CH02_CURR_RAID = 3469,
        EPS_VIP_CH02_POWE_RAID = 3470,
        EPS_VIP_CH03_VOLT_RAID = 3471,
        EPS_VIP_CH03_CURR_RAID = 3472,
        EPS_VIP_CH03_POWE_RAID = 3473,
        EPS_VIP_CH04_VOLT_RAID = 3474,
        EPS_VIP_CH04_CURR_RAID = 3475,
        EPS_VIP_CH04_POWE_RAID = 3476,
        EPS_VIP_CH05_VOLT_RAID = 3477,
        EPS_VIP_CH05_CURR_RAID = 3478,
        EPS_VIP_CH05_POWE_RAID = 3479,
        EPS_VIP_CH06_VOLT_RAID = 3480,
        EPS_VIP_CH06_CURR_RAID = 3481,
        EPS_VIP_CH06_POWE_RAID = 3482,
        EPS_VIP_CH07_VOLT_RAID = 3483,
        EPS_VIP_CH07_CURR_RAID = 3484,
        EPS_VIP_CH07_POWE_RAID = 3485,
        EPS_VIP_CH08_VOLT_RAID = 3486,
        EPS_VIP_CH08_CURR_RAID = 3487,
        EPS_VIP_CH08_POWE_RAID = 3488,
        EPS_VIP_CH09_VOLT_RAID = 3489,
        EPS_VIP_CH09_CURR_RAID = 3490,
        EPS_VIP_CH09_POWE_RAID = 3491,
        EPS_VIP_CH10_VOLT_RAID = 3492,
        EPS_VIP_CH10_CURR_RAID = 3493,
        EPS_VIP_CH10_POWE_RAID = 3494,
        EPS_VIP_CH11_VOLT_RAID = 3495,
        EPS_VIP_CH11_CURR_RAID = 3496,
        EPS_VIP_CH11_POWE_RAID = 3497,
        EPS_VIP_CH12_VOLT_RAID = 3498,
        EPS_VIP_CH12_CURR_RAID = 3499,
        EPS_VIP_CH12_POWE_RAID = 3500,
        EPS_VIP_CH13_VOLT_RAID = 3501,
        EPS_VIP_CH13_CURR_RAID = 3502,
        EPS_VIP_CH13_POWE_RAID = 3503,
        EPS_VIP_CH14_VOLT_RAID = 3504,
        EPS_VIP_CH14_CURR_RAID = 3505,
        EPS_VIP_CH14_POWE_RAID = 3506,
        EPS_VOLT_BRDSUP_RAID = 3507,
        EPS_TEMP_MCU_RAID = 3508,
        EPS_VIP_VOLT_INPUT_RAID = 3509,
        EPS_VIP_CURR_INPUT_RAID = 3510,
        EPS_VIP_POWE_INPUT_RAID = 3511,
        EPS_VIP_VOLT_DIST_INPUT_RAID = 3512,
        EPS_VIP_CURR_DIST_INPUT_RAID = 3513,
        EPS_VIP_POWE_DIST_INPUT_RAID = 3514,
        EPS_VIP_VOLT_BAT_INPUT_RAID = 3515,
        EPS_VIP_CURR_BAT_INPUT_RAID = 3516,
        EPS_VIP_POWE_BAT_INPUT_RAID = 3517,
        EPS_VIP_VOLT_VD0_RAID = 3518,
        EPS_VIP_CURR_VD0_RAID = 3519,
        EPS_VIP_POWE_VD0_RAID = 3520,
        EPS_VIP_VOLT_VD1_RAID = 3521,
        EPS_VIP_CURR_VD1_RAID = 3522,
        EPS_VIP_POWE_VD1_RAID = 3523,
        EPS_VIP_VOLT_VD2_RAID = 3524,
        EPS_VIP_CURR_VD2_RAID = 3525,
        EPS_VIP_POWE_VD2_RAID = 3526,
        EPS_VIP_VOLT_VD3_RAID = 3527,
        EPS_VIP_CURR_VD3_RAID = 3528,
        EPS_VIP_POWE_VD3_RAID = 3529,
        EPS_VIP_VOLT_VD4_RAID = 3530,
        EPS_VIP_CURR_VD4_RAID = 3531,
        EPS_VIP_POWE_VD4_RAID = 3532,
        EPS_VIP_VOLT_VD5_RAID = 3533,
        EPS_VIP_CURR_VD5_RAID = 3534,
        EPS_VIP_POWE_VD5_RAID = 3535,
        EPS_VIP_VOLT_VD6_RAID = 3536,
        EPS_VIP_CURR_VD6_RAID = 3537,
        EPS_VIP_POWE_VD6_RAID = 3538,
        EPS_STAT_BUID = 3539,
        EPS_VOLT_BP1_INPUT_RAWID = 3540,
        EPS_CURR_BP1_INPUT_RAWID = 3541,
        EPS_POWE_BP1_INPUT_RAWID = 3542,
        EPS_STAT_BP1_RAWID = 3543,
        EPS_VOLT_BP1_CELL1_RAWID = 3544,
        EPS_VOLT_BP1_CELL2_RAWID = 3545,
        EPS_VOLT_BP1_CELL3_RAWID = 3546,
        EPS_VOLT_BP1_CELL4_RAWID = 3547,
        EPS_BAT_TEMP1_BP1_RAWID = 3548,
        EPS_BAT_TEMP2_BP1_RAWID = 3549,
        EPS_BAT_TEMP3_BP1_RAWID = 3550,
        EPS_VOLT_BP2_INPUT_RAWID = 3551,
        EPS_CURR_BP2_INPUT_RAWID = 3552,
        EPS_POWE_BP2_INPUT_RAWID = 3553,
        EPS_STAT_BP2_RAWID = 3554,
        EPS_VOLT_BP2_CELL1_RAWID = 3555,
        EPS_VOLT_BP2_CELL2_RAWID = 3556,
        EPS_VOLT_BP2_CELL3_RAWID = 3557,
        EPS_VOLT_BP2_CELL4_RAWID = 3558,
        EPS_BAT_TEMP1_BP2_RAWID = 3559,
        EPS_BAT_TEMP2_BP2_RAWID = 3560,
        EPS_BAT_TEMP3_BP2_RAWID = 3561,
        EPS_VOLT_BP3_INPUT_RAWID = 3562,
        EPS_CURR_BP3_INPUT_RAWID = 3563,
        EPS_POWE_BP3_INPUT_RAWID = 3564,
        EPS_STAT_BP3_RAWID = 3565,
        EPS_VOLT_BP3_CELL1_RAWID = 3566,
        EPS_VOLT_BP3_CELL2_RAWID = 3567,
        EPS_VOLT_BP3_CELL3_RAWID = 3568,
        EPS_VOLT_BP3_CELL4_RAWID = 3569,
        EPS_BAT_TEMP1_BP3_RAWID = 3570,
        EPS_BAT_TEMP2_BP3_RAWID = 3571,
        EPS_BAT_TEMP3_BP3_RAWID = 3572,
        EPS_VOLT_BP1_INPUT_ENGID = 3573,
        EPS_CURR_BP1_INPUT_ENGID = 3574,
        EPS_POWE_BP1_INPUT_ENGID = 3575,
        EPS_STAT_BP1_ENGID = 3576,
        EPS_VOLT_BP1_CELL1_ENGID = 3577,
        EPS_VOLT_BP1_CELL2_ENGID = 3578,
        EPS_VOLT_BP1_CELL3_ENGID = 3579,
        EPS_VOLT_BP1_CELL4_ENGID = 3580,
        EPS_BAT_TEMP1_BP1_ENGID = 3581,
        EPS_BAT_TEMP2_BP1_ENGID = 3582,
        EPS_BAT_TEMP3_BP1_ENGID = 3583,
        EPS_VOLT_BP2_INPUT_ENGID = 3584,
        EPS_CURR_BP2_INPUT_ENGID = 3585,
        EPS_POWE_BP2_INPUT_ENGID = 3586,
        EPS_STAT_BP2_ENGID = 3587,
        EPS_VOLT_BP2_CELL1_ENGID = 3588,
        EPS_VOLT_BP2_CELL2_ENGID = 3589,
        EPS_VOLT_BP2_CELL3_ENGID = 3590,
        EPS_VOLT_BP2_CELL4_ENGID = 3591,
        EPS_BAT_TEMP1_BP2_ENGID = 3592,
        EPS_BAT_TEMP2_BP2_ENGID = 3593,
        EPS_BAT_TEMP3_BP2_ENGID = 3594,
        EPS_VOLT_BP3_INPUT_ENGID = 3595,
        EPS_CURR_BP3_INPUT_ENGID = 3596,
        EPS_POWE_BP3_INPUT_ENGID = 3597,
        EPS_STAT_BP3_ENGID = 3598,
        EPS_VOLT_BP3_CELL1_ENGID = 3599,
        EPS_VOLT_BP3_CELL2_ENGID = 3600,
        EPS_VOLT_BP3_CELL3_ENGID = 3601,
        EPS_VOLT_BP3_CELL4_ENGID = 3602,
        EPS_BAT_TEMP1_BP3_ENGID = 3603,
        EPS_BAT_TEMP2_BP3_ENGID = 3604,
        EPS_BAT_TEMP3_BP3_ENGID = 3605,
        EPS_VOLT_BP1_INPUT_RAID = 3606,
        EPS_CURR_BP1_INPUT_RAID = 3607,
        EPS_POWE_BP1_INPUT_RAID = 3608,
        EPS_STAT_BP1_RAID = 3609,
        EPS_VOLT_BP1_CELL1_RAID = 3610,
        EPS_VOLT_BP1_CELL2_RAID = 3611,
        EPS_VOLT_BP1_CELL3_RAID = 3612,
        EPS_VOLT_BP1_CELL4_RAID = 3613,
        EPS_BAT_TEMP1_BP1_RAID = 3614,
        EPS_BAT_TEMP2_BP1_RAID = 3615,
        EPS_BAT_TEMP3_BP1_RAID = 3616,
        EPS_VOLT_BP2_INPUT_RAID = 3617,
        EPS_CURR_BP2_INPUT_RAID = 3618,
        EPS_POWE_BP2_INPUT_RAID = 3619,
        EPS_STAT_BP2_RAID = 3620,
        EPS_VOLT_BP2_CELL1_RAID = 3621,
        EPS_VOLT_BP2_CELL2_RAID = 3622,
        EPS_VOLT_BP2_CELL3_RAID = 3623,
        EPS_VOLT_BP2_CELL4_RAID = 3624,
        EPS_BAT_TEMP1_BP2_RAID = 3625,
        EPS_BAT_TEMP2_BP2_RAID = 3626,
        EPS_BAT_TEMP3_BP2_RAID = 3627,
        EPS_VOLT_BP3_INPUT_RAID = 3628,
        EPS_CURR_BP3_INPUT_RAID = 3629,
        EPS_POWE_BP3_INPUT_RAID = 3630,
        EPS_STAT_BP3_RAID = 3631,
        EPS_VOLT_BP3_CELL1_RAID = 3632,
        EPS_VOLT_BP3_CELL2_RAID = 3633,
        EPS_VOLT_BP3_CELL3_RAID = 3634,
        EPS_VOLT_BP3_CELL4_RAID = 3635,
        EPS_BAT_TEMP1_BP3_RAID = 3636,
        EPS_BAT_TEMP2_BP3_RAID = 3637,
        EPS_BAT_TEMP3_BP3_RAID = 3638,
        EPS_VOLT_VD0_RAWID = 3639,
        EPS_VOLT_VD1_RAWID = 3640,
        EPS_VOLT_VD2_RAWID = 3641,
        EPS_VOLT_VD0_ENGID = 3642,
        EPS_VOLT_VD1_ENGID = 3643,
        EPS_VOLT_VD2_ENGID = 3644,
        EPS_VOLT_VD0_RAID = 3645,
        EPS_VOLT_VD1_RAID = 3646,
        EPS_VOLT_VD2_RAID = 3647,
        EPS_BAT_STATID = 3648,
        EPS_BAT_TEMP2_RAWID = 3649,
        EPS_BAT_TEMP3_RAWID = 3650,
        EPS_BAT_TEMP2_ENGID = 3651,
        EPS_BAT_TEMP3_ENGID = 3652,
        EPS_BAT_TEMP2_RAID = 3653,
        EPS_BAT_TEMP3_RAID = 3654,
        EPS_CC1_VOLT_IN_MPPT_RAWID = 3655,
        EPS_CC2_VOLT_IN_MPPT_RAWID = 3656,
        EPS_CC3_VOLT_IN_MPPT_RAWID = 3657,
        EPS_CC4_VOLT_IN_MPPT_RAWID = 3658,
        EPS_CC5_VOLT_IN_MPPT_RAWID = 3659,
        EPS_CC1_CURR_IN_MPPT_RAWID = 3660,
        EPS_CC2_CURR_IN_MPPT_RAWID = 3661,
        EPS_CC3_CURR_IN_MPPT_RAWID = 3662,
        EPS_CC4_CURR_IN_MPPT_RAWID = 3663,
        EPS_CC5_CURR_IN_MPPT_RAWID = 3664,
        EPS_CC1_VOLT_OU_MPPT_RAWID = 3665,
        EPS_CC2_VOLT_OU_MPPT_RAWID = 3666,
        EPS_CC3_VOLT_OU_MPPT_RAWID = 3667,
        EPS_CC4_VOLT_OU_MPPT_RAWID = 3668,
        EPS_CC5_VOLT_OU_MPPT_RAWID = 3669,
        EPS_CC1_CURR_OU_MPPT_RAWID = 3670,
        EPS_CC2_CURR_OU_MPPT_RAWID = 3671,
        EPS_CC3_CURR_OU_MPPT_RAWID = 3672,
        EPS_CC4_CURR_OU_MPPT_RAWID = 3673,
        EPS_CC5_CURR_OU_MPPT_RAWID = 3674,
        EPS_CC1_VOLT_IN_MPPT_ENGID = 3675,
        EPS_CC2_VOLT_IN_MPPT_ENGID = 3676,
        EPS_CC3_VOLT_IN_MPPT_ENGID = 3677,
        EPS_CC4_VOLT_IN_MPPT_ENGID = 3678,
        EPS_CC5_VOLT_IN_MPPT_ENGID = 3679,
        EPS_CC1_CURR_IN_MPPT_ENGID = 3680,
        EPS_CC2_CURR_IN_MPPT_ENGID = 3681,
        EPS_CC3_CURR_IN_MPPT_ENGID = 3682,
        EPS_CC4_CURR_IN_MPPT_ENGID = 3683,
        EPS_CC5_CURR_IN_MPPT_ENGID = 3684,
        EPS_CC1_VOLT_OU_MPPT_ENGID = 3685,
        EPS_CC2_VOLT_OU_MPPT_ENGID = 3686,
        EPS_CC3_VOLT_OU_MPPT_ENGID = 3687,
        EPS_CC4_VOLT_OU_MPPT_ENGID = 3688,
        EPS_CC5_VOLT_OU_MPPT_ENGID = 3689,
        EPS_CC1_CURR_OU_MPPT_ENGID = 3690,
        EPS_CC2_CURR_OU_MPPT_ENGID = 3691,
        EPS_CC3_CURR_OU_MPPT_ENGID = 3692,
        EPS_CC4_CURR_OU_MPPT_ENGID = 3693,
        EPS_CC5_CURR_OU_MPPT_ENGID = 3694,
        EPS_CC1_VOLT_IN_MPPT_RAID = 3695,
        EPS_CC2_VOLT_IN_MPPT_RAID = 3696,
        EPS_CC3_VOLT_IN_MPPT_RAID = 3697,
        EPS_CC4_VOLT_IN_MPPT_RAID = 3698,
        EPS_CC5_VOLT_IN_MPPT_RAID = 3699,
        EPS_CC1_CURR_IN_MPPT_RAID = 3700,
        EPS_CC2_CURR_IN_MPPT_RAID = 3701,
        EPS_CC3_CURR_IN_MPPT_RAID = 3702,
        EPS_CC4_CURR_IN_MPPT_RAID = 3703,
        EPS_CC5_CURR_IN_MPPT_RAID = 3704,
        EPS_CC1_VOLT_OU_MPPT_RAID = 3705,
        EPS_CC2_VOLT_OU_MPPT_RAID = 3706,
        EPS_CC3_VOLT_OU_MPPT_RAID = 3707,
        EPS_CC4_VOLT_OU_MPPT_RAID = 3708,
        EPS_CC5_VOLT_OU_MPPT_RAID = 3709,
        EPS_CC1_CURR_OU_MPPT_RAID = 3710,
        EPS_CC2_CURR_OU_MPPT_RAID = 3711,
        EPS_CC3_CURR_OU_MPPT_RAID = 3712,
        EPS_CC4_CURR_OU_MPPT_RAID = 3713,
        EPS_CC5_CURR_OU_MPPT_RAID = 3714,
        EPS_CH_STARTUP_ENA_BFID = 3715,
        EPS_CH_STARTUP_KEYID = 3716,
        EPS_CH_LATCHOFF_ENA_BFID = 3717,
        EPS_CH_LATCHOFF_KEYID = 3718,
        EPS_TTC_WDG_TIMEOUTID = 3719,
        EPS_TTC_WDG_TIMEOUT_KEYID = 3720,
        EPS_CH_STARTUP_DELAY_CH1ID = 3721,
        EPS_CH_LATCHOFF_DELAY_CH1ID = 3722,
        EPS_SAFETY_VOLT_LOTHRID = 3723,
        EPS_SAFETY_VOLT_HITHRID = 3724,
        EPS_LOTHR_BP1_HEATERID = 3725,
        EPS_LOTHR_BP2_HEATERID = 3726,
        EPS_LOTHR_BP3_HEATERID = 3727,
        EPS_HITHR_BP1_HEATERID = 3728,
        EPS_HITHR_BP2_HEATERID = 3729,
        EPS_HITHR_BP3_HEATERID = 3730,
        EPS_LOTHR_BP1_UNBALID = 3731,
        EPS_LOTHR_BP2_UNBALID = 3732,
        EPS_LOTHR_BP3_UNBALID = 3733,
        EPS_HITHR_BP1_UNBALID = 3734,
        EPS_HITHR_BP2_UNBALID = 3735,
        EPS_HITHR_BP3_UNBALID = 3736,
        EPS_MCU_TEMP_BIASID = 3737,
        EPS_MCU_TEMP_PREMULID = 3738,
        EPS_MCU_TEMP_POSDIVID = 3739,
        EPS_BP1_TEMP1_BIASID = 3740,
        EPS_BP1_TEMP2_BIASID = 3741,
        EPS_BP1_TEMP3_BIASID = 3742,
        EPS_BP2_TEMP1_BIASID = 3743,
        EPS_BP2_TEMP2_BIASID = 3744,
        EPS_BP2_TEMP3_BIASID = 3745,
        EPS_BP3_TEMP1_BIASID = 3746,
        EPS_BP3_TEMP2_BIASID = 3747,
        EPS_BP3_TEMP3_BIASID = 3748,
        EPS_BP1_TEMP1_PREMULID = 3749,
        EPS_BP1_TEMP2_PREMULID = 3750,
        EPS_BP1_TEMP3_PREMULID = 3751,
        EPS_BP2_TEMP1_PREMULID = 3752,
        EPS_BP2_TEMP2_PREMULID = 3753,
        EPS_BP2_TEMP3_PREMULID = 3754,
        EPS_BP3_TEMP1_PREMULID = 3755,
        EPS_BP3_TEMP2_PREMULID = 3756,
        EPS_BP3_TEMP3_PREMULID = 3757,
        EPS_BP1_TEMP1_POSDIVID = 3758,
        EPS_BP1_TEMP2_POSDIVID = 3759,
        EPS_BP1_TEMP3_POSDIVID = 3760,
        EPS_BP2_TEMP1_POSDIVID = 3761,
        EPS_BP2_TEMP2_POSDIVID = 3762,
        EPS_BP2_TEMP3_POSDIVID = 3763,
        EPS_BP3_TEMP1_POSDIVID = 3764,
        EPS_BP3_TEMP2_POSDIVID = 3765,
        EPS_BP3_TEMP3_POSDIVID = 3766,
        EPS_BOARD_IDENTIFIERID = 3767,
        EPS_BOARD_IDENTIFIER_KEYID = 3768,
        EPS_RAVG_STRENGTH_P2ID = 3769,
        EPS_AUTO_HEAT_ENA_BP1ID = 3770,
        EPS_AUTO_HEAT_ENA_BP2ID = 3771,
        EPS_AUTO_HEAT_ENA_BP3ID = 3772,
        EPS_AUTO_BAL_ENA_BP1ID = 3773,
        EPS_AUTO_BAL_ENA_BP2ID = 3774,
        EPS_AUTO_BAL_ENA_BP3ID = 3775,
        EPS_VD1_ALWAYS_ENAID = 3776,
        EPS_VD1_ALWAYS_DISAID = 3777,
        EPS_CH_FORCE_ENA_USE_BFID = 3778,
        EPS_CH_STARTUP_ENA_USE_BFID = 3779,
        EPS_CH_LATCHOFF_ENA_USE_BFID = 3780,
        EPS_VD1_ALLOC_CH_BFID = 3781,
        EPS_SWCI_CH_CMD_ENA_BFID = 3782,
        EPS_SWCI_CH_CMD_DISA_BFID = 3783,
        EPS_TTC_I2C_SLAVE_ADDRID = 3784,
        EPS_CONF_NVM_SAVE_CNTRID = 3785,
        EPS_CONF_NVM_SAVE_CHKSID = 3786,
        EPS_RST_CAUSEID = 3787,
        EPS_RST_CNTR_PWRONID = 3788,
        EPS_RST_CNTR_WDGID = 3789,
        EPS_RST_CNTR_CMDID = 3790,
        EPS_RST_CNTR_MCUID = 3791,
        EPS_RST_CNTR_EMLOPOID = 3792,
        EPS_RST_CODE_MCU_RAWID = 3793,
        EPS_EMLOPO_VOLT_LOTHRID = 3794,
        EPS_EMLOPO_VOLT_HITHRID = 3795,
        EPS_EMLOPO_PERIODID = 3796,
        EPS_SAFETY_VOLT_LOTHR_USEDID = 3797,
        EPS_SAFETY_VOLT_HITHR_USEDID = 3798,
        EPS_SAFETY_LINGERID = 3799,
        EPS_TTC_WDG_TIMOUT_USEDID = 3800,
        EPS_TTC_PREVCMD_ELAPSEDID = 3801,
        EPS_STIDID = 3802,
        EPS_IVIDID = 3803,
        EPS_BID_USEDID = 3804,
        EPS_BOOT_RESUME_SHORTID = 3805,
        EPS_CONF_PARAM_CHANGEDID = 3806,
        EPS_VIP_VOLT_INPUT_RAWID = 3807,
        EPS_VIP_CURR_INPUT_RAWID = 3808,
        EPS_VIP_POWE_INPUT_RAWID = 3809,
        EPS_VIP_CC1_OUTPUT_VOLT_RAWID = 3810,
        EPS_VIP_CC1_OUTPUT_CURR_RAWID = 3811,
        EPS_VIP_CC1_OUTPUT_POWE_RAWID = 3812,
        EPS_VIP_CC2_OUTPUT_VOLT_RAWID = 3813,
        EPS_VIP_CC2_OUTPUT_CURR_RAWID = 3814,
        EPS_VIP_CC2_OUTPUT_POWE_RAWID = 3815,
        EPS_VIP_CC3_OUTPUT_VOLT_RAWID = 3816,
        EPS_VIP_CC3_OUTPUT_CURR_RAWID = 3817,
        EPS_VIP_CC3_OUTPUT_POWE_RAWID = 3818,
        EPS_VIP_CC4_OUTPUT_VOLT_RAWID = 3819,
        EPS_VIP_CC4_OUTPUT_CURR_RAWID = 3820,
        EPS_VIP_CC4_OUTPUT_POWE_RAWID = 3821,
        EPS_VIP_CC5_OUTPUT_VOLT_RAWID = 3822,
        EPS_VIP_CC5_OUTPUT_CURR_RAWID = 3823,
        EPS_VIP_CC5_OUTPUT_POWE_RAWID = 3824,
        EPS_VIP_CC1_OUTPUT_VOLT_ENGID = 3825,
        EPS_VIP_CC1_OUTPUT_CURR_ENGID = 3826,
        EPS_VIP_CC1_OUTPUT_POWE_ENGID = 3827,
        EPS_VIP_CC2_OUTPUT_VOLT_ENGID = 3828,
        EPS_VIP_CC2_OUTPUT_CURR_ENGID = 3829,
        EPS_VIP_CC2_OUTPUT_POWE_ENGID = 3830,
        EPS_VIP_CC3_OUTPUT_VOLT_ENGID = 3831,
        EPS_VIP_CC3_OUTPUT_CURR_ENGID = 3832,
        EPS_VIP_CC3_OUTPUT_POWE_ENGID = 3833,
        EPS_VIP_CC4_OUTPUT_VOLT_ENGID = 3834,
        EPS_VIP_CC4_OUTPUT_CURR_ENGID = 3835,
        EPS_VIP_CC4_OUTPUT_POWE_ENGID = 3836,
        EPS_VIP_CC5_OUTPUT_VOLT_ENGID = 3837,
        EPS_VIP_CC5_OUTPUT_CURR_ENGID = 3838,
        EPS_VIP_CC5_OUTPUT_POWE_ENGID = 3839,
        EPS_VIP_CC1_OUTPUT_VOLT_RAID = 3840,
        EPS_VIP_CC1_OUTPUT_CURR_RAID = 3841,
        EPS_VIP_CC1_OUTPUT_POWE_RAID = 3842,
        EPS_VIP_CC2_OUTPUT_VOLT_RAID = 3843,
        EPS_VIP_CC2_OUTPUT_CURR_RAID = 3844,
        EPS_VIP_CC2_OUTPUT_POWE_RAID = 3845,
        EPS_VIP_CC3_OUTPUT_VOLT_RAID = 3846,
        EPS_VIP_CC3_OUTPUT_CURR_RAID = 3847,
        EPS_VIP_CC3_OUTPUT_POWE_RAID = 3848,
        EPS_VIP_CC4_OUTPUT_VOLT_RAID = 3849,
        EPS_VIP_CC4_OUTPUT_CURR_RAID = 3850,
        EPS_VIP_CC4_OUTPUT_POWE_RAID = 3851,
        EPS_VIP_CC5_OUTPUT_VOLT_RAID = 3852,
        EPS_VIP_CC5_OUTPUT_CURR_RAID = 3853,
        EPS_VIP_CC5_OUTPUT_POWE_RAID = 3854,
        EPS_VIP_VOLT_DIST_INPUT_RAWID = 3855,
        EPS_VIP_CURR_DIST_INPUT_RAWID = 3856,
        EPS_VIP_POWE_DIST_INPUT_RAWID = 3857,
        EPS_VIP_VOLT_BAT_INPUT_RAWID = 3858,
        EPS_VIP_CURR_BAT_INPUT_RAWID = 3859,
        EPS_VIP_POWE_BAT_INPUT_RAWID = 3860,
        EPS_VIP_OUTPUT_VOLT_RAWID = 3861,
        EPS_VIP_OUTPUT_CURR_RAWID = 3862,
        EPS_VIP_OUTPUT_POWE_RAWID = 3863,
        EPS_VIP_OUTPUT_VOLT_ENGID = 3864,
        EPS_VIP_OUTPUT_CURR_ENGID = 3865,
        EPS_VIP_OUTPUT_POWE_ENGID = 3866,
        EPS_VIP_OUTPUT_VOLT_RAID = 3867,
        EPS_VIP_OUTPUT_CURR_RAID = 3868,
        EPS_VIP_OUTPUT_POWE_RAID = 3869,
        EPS_ADC_MCU_TEMP_V25T30ID = 3870,
        EPS_ADC_MCU_TEMP_V25T85ID = 3871
    };
    inline Parameter<uint8_t> EPS_MODE(0);
    inline Parameter<uint8_t> EPS_CONF(0);
    inline Parameter<uint8_t> EPS_RESET_CAUSE(0);
    inline Parameter<uint32_t> EPS_UPTIME(0);
    inline Parameter<uint16_t> EPS_ERROR(0);
    inline Parameter<uint16_t> EPS_RC_CNT_PWRON(0);
    inline Parameter<uint16_t> EPS_RC_CNT_WDG(0);
    inline Parameter<uint16_t> EPS_RC_CNT_CMD(0);
    inline Parameter<uint16_t> EPS_RC_CNT_MCU(0);
    inline Parameter<uint16_t> EPS_RC_CNT_EMLOPO(0);
    inline Parameter<uint16_t> EPS_PREVCMD_ELAPSED(0);
    inline Parameter<uint32_t> EPS_UNIX_TIME(0);
    inline Parameter<uint8_t> EPS_UNIX_YEAR(0);
    inline Parameter<uint8_t> EPS_UNIX_MONTH(0);
    inline Parameter<uint8_t> EPS_UNIX_DAY(0);
    inline Parameter<uint8_t> EPS_UNIX_HOUR(0);
    inline Parameter<uint8_t> EPS_UNIX_MINUTE(0);
    inline Parameter<uint8_t> EPS_UNIX_SECOND(0);
    inline Parameter<uint16_t> EPS_STAT_CH_ON(0);
    inline Parameter<uint16_t> EPS_STAT_CH_EXT_ON(0);
    inline Parameter<uint16_t> EPS_STAT_CH_OCF(0);
    inline Parameter<uint16_t> EPS_STAT_CH_EXT_OCF(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH00(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH01(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH02(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH03(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH04(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH05(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH06(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH07(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH08(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH09(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH10(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH11(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH12(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH13(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH14(0);
    inline Parameter<uint16_t> EPS_OCF_CNT_CH15(0);
    inline Parameter<uint8_t> EPS_ABF_PLACED_0(0);
    inline Parameter<uint8_t> EPS_ABF_PLACED_1(0);
    inline Parameter<uint16_t> EPS_VOLT_BRDSUP_RAW(0);
    inline Parameter<uint16_t> EPS_TEMP_MCU_RAW(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD0_RAW(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD1_RAW(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD2_RAW(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD3_RAW(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD4_RAW(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD5_RAW(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD6_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD0_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD1_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD2_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD3_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD4_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD5_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD6_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD0_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD1_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD2_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD3_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD4_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD5_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD6_RAW(0);
    inline Parameter<int16_t> EPS_VOLT_BRDSUP_ENG(0);
    inline Parameter<int16_t> EPS_TEMP_MCU_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_DIST_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_DIST_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_DIST_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_BAT_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_BAT_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_BAT_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD0_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD0_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD0_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD1_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD1_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD1_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD2_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD2_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD2_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD3_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD3_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD3_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD4_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD4_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD4_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD5_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD5_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD5_ENG(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD6_ENG(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD6_ENG(0);
    inline Parameter<uint16_t> EPS_VIP_CH00_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH00_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH00_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH01_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH01_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH01_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH02_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH02_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH02_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH03_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH03_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH03_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH04_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH04_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH04_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH05_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH05_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH05_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH06_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH06_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH06_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH07_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH07_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH07_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH08_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH08_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH08_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH09_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH09_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH09_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH10_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH10_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH10_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH11_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH11_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH11_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH12_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH12_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH12_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH13_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH13_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH13_POWE_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH14_VOLT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH14_CURR_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CH14_POWE_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CH00_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH00_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH00_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH01_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH01_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH01_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH02_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH02_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH02_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH03_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH03_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH03_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH04_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH04_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH04_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH05_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH05_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH05_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH06_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH06_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH06_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH07_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH07_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH07_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH08_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH08_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH08_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH09_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH09_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH09_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH10_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH10_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH10_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH11_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH11_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH11_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH12_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH12_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH12_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH13_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH13_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH13_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH14_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH14_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH14_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CH00_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH00_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH00_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH01_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH01_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH01_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH02_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH02_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH02_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH03_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH03_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH03_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH04_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH04_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH04_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH05_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH05_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH05_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH06_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH06_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH06_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH07_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH07_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH07_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH08_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH08_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH08_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH09_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH09_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH09_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH10_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH10_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH10_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH11_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH11_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH11_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH12_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH12_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH12_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH13_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH13_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH13_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH14_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH14_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CH14_POWE_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BRDSUP_RA(0);
    inline Parameter<int16_t> EPS_TEMP_MCU_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_DIST_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_DIST_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_DIST_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_BAT_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_BAT_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_BAT_INPUT_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD0_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD0_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD0_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD1_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD1_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD1_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD2_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD2_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD2_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD3_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD3_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD3_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD4_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD4_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD4_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD5_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD5_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD5_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_VD6_RA(0);
    inline Parameter<int16_t> EPS_VIP_CURR_VD6_RA(0);
    inline Parameter<int16_t> EPS_VIP_POWE_VD6_RA(0);
    inline Parameter<int16_t> EPS_STAT_BU(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_CURR_BP1_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_POWE_BP1_INPUT_RAW(0);
    inline Parameter<uint16_t> EPS_STAT_BP1_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP1_CELL1_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP1_CELL2_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP1_CELL3_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP1_CELL4_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP1_BP1_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP2_BP1_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP3_BP1_RAW(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_CURR_BP2_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_POWE_BP2_INPUT_RAW(0);
    inline Parameter<uint16_t> EPS_STAT_BP2_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP2_CELL1_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP2_CELL2_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP2_CELL3_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP2_CELL4_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP1_BP2_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP2_BP2_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP3_BP2_RAW(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_CURR_BP3_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_POWE_BP3_INPUT_RAW(0);
    inline Parameter<uint16_t> EPS_STAT_BP3_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP3_CELL1_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP3_CELL2_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP3_CELL3_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_BP3_CELL4_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP1_BP3_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP2_BP3_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP3_BP3_RAW(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_CURR_BP1_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_POWE_BP1_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_STAT_BP1_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_CELL1_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_CELL2_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_CELL3_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_CELL4_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP1_BP1_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP2_BP1_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP3_BP1_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_CURR_BP2_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_POWE_BP2_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_STAT_BP2_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_CELL1_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_CELL2_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_CELL3_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_CELL4_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP1_BP2_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP2_BP2_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP3_BP2_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_CURR_BP3_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_POWE_BP3_INPUT_ENG(0);
    inline Parameter<int16_t> EPS_STAT_BP3_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_CELL1_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_CELL2_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_CELL3_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_CELL4_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP1_BP3_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP2_BP3_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP3_BP3_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_INPUT_RA(0);
    inline Parameter<int16_t> EPS_CURR_BP1_INPUT_RA(0);
    inline Parameter<int16_t> EPS_POWE_BP1_INPUT_RA(0);
    inline Parameter<int16_t> EPS_STAT_BP1_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_CELL1_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_CELL2_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_CELL3_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP1_CELL4_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP1_BP1_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP2_BP1_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP3_BP1_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_INPUT_RA(0);
    inline Parameter<int16_t> EPS_CURR_BP2_INPUT_RA(0);
    inline Parameter<int16_t> EPS_POWE_BP2_INPUT_RA(0);
    inline Parameter<int16_t> EPS_STAT_BP2_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_CELL1_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_CELL2_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_CELL3_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP2_CELL4_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP1_BP2_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP2_BP2_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP3_BP2_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_INPUT_RA(0);
    inline Parameter<int16_t> EPS_CURR_BP3_INPUT_RA(0);
    inline Parameter<int16_t> EPS_POWE_BP3_INPUT_RA(0);
    inline Parameter<int16_t> EPS_STAT_BP3_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_CELL1_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_CELL2_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_CELL3_RA(0);
    inline Parameter<int16_t> EPS_VOLT_BP3_CELL4_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP1_BP3_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP2_BP3_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP3_BP3_RA(0);
    inline Parameter<uint16_t> EPS_VOLT_VD0_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_VD1_RAW(0);
    inline Parameter<uint16_t> EPS_VOLT_VD2_RAW(0);
    inline Parameter<int16_t> EPS_VOLT_VD0_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_VD1_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_VD2_ENG(0);
    inline Parameter<int16_t> EPS_VOLT_VD0_RA(0);
    inline Parameter<int16_t> EPS_VOLT_VD1_RA(0);
    inline Parameter<int16_t> EPS_VOLT_VD2_RA(0);
    inline Parameter<int16_t> EPS_BAT_STAT(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP2_RAW(0);
    inline Parameter<uint16_t> EPS_BAT_TEMP3_RAW(0);
    inline Parameter<int16_t> EPS_BAT_TEMP2_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP3_ENG(0);
    inline Parameter<int16_t> EPS_BAT_TEMP2_RA(0);
    inline Parameter<int16_t> EPS_BAT_TEMP3_RA(0);
    inline Parameter<uint16_t> EPS_CC1_VOLT_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC2_VOLT_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC3_VOLT_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC4_VOLT_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC5_VOLT_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC1_CURR_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC2_CURR_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC3_CURR_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC4_CURR_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC5_CURR_IN_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC1_VOLT_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC2_VOLT_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC3_VOLT_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC4_VOLT_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC5_VOLT_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC1_CURR_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC2_CURR_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC3_CURR_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC4_CURR_OU_MPPT_RAW(0);
    inline Parameter<uint16_t> EPS_CC5_CURR_OU_MPPT_RAW(0);
    inline Parameter<int16_t> EPS_CC1_VOLT_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC2_VOLT_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC3_VOLT_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC4_VOLT_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC5_VOLT_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC1_CURR_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC2_CURR_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC3_CURR_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC4_CURR_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC5_CURR_IN_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC1_VOLT_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC2_VOLT_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC3_VOLT_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC4_VOLT_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC5_VOLT_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC1_CURR_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC2_CURR_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC3_CURR_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC4_CURR_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC5_CURR_OU_MPPT_ENG(0);
    inline Parameter<int16_t> EPS_CC1_VOLT_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC2_VOLT_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC3_VOLT_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC4_VOLT_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC5_VOLT_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC1_CURR_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC2_CURR_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC3_CURR_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC4_CURR_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC5_CURR_IN_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC1_VOLT_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC2_VOLT_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC3_VOLT_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC4_VOLT_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC5_VOLT_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC1_CURR_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC2_CURR_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC3_CURR_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC4_CURR_OU_MPPT_RA(0);
    inline Parameter<int16_t> EPS_CC5_CURR_OU_MPPT_RA(0);
    inline Parameter<uint32_t> EPS_CH_STARTUP_ENA_BF(0);
    inline Parameter<uint32_t> EPS_CH_STARTUP_KEY(0);
    inline Parameter<uint32_t> EPS_CH_LATCHOFF_ENA_BF(0);
    inline Parameter<uint32_t> EPS_CH_LATCHOFF_KEY(0);
    inline Parameter<uint16_t> EPS_TTC_WDG_TIMEOUT(0);
    inline Parameter<uint16_t> EPS_TTC_WDG_TIMEOUT_KEY(0);
    inline Parameter<uint16_t> EPS_CH_STARTUP_DELAY_CH1(0);
    inline Parameter<uint16_t> EPS_CH_LATCHOFF_DELAY_CH1(0);
    inline Parameter<uint16_t> EPS_SAFETY_VOLT_LOTHR(0);
    inline Parameter<uint16_t> EPS_SAFETY_VOLT_HITHR(0);
    inline Parameter<int16_t> EPS_LOTHR_BP1_HEATER(0);
    inline Parameter<int16_t> EPS_LOTHR_BP2_HEATER(0);
    inline Parameter<int16_t> EPS_LOTHR_BP3_HEATER(0);
    inline Parameter<int16_t> EPS_HITHR_BP1_HEATER(0);
    inline Parameter<int16_t> EPS_HITHR_BP2_HEATER(0);
    inline Parameter<int16_t> EPS_HITHR_BP3_HEATER(0);
    inline Parameter<int16_t> EPS_LOTHR_BP1_UNBAL(0);
    inline Parameter<int16_t> EPS_LOTHR_BP2_UNBAL(0);
    inline Parameter<int16_t> EPS_LOTHR_BP3_UNBAL(0);
    inline Parameter<int16_t> EPS_HITHR_BP1_UNBAL(0);
    inline Parameter<int16_t> EPS_HITHR_BP2_UNBAL(0);
    inline Parameter<int16_t> EPS_HITHR_BP3_UNBAL(0);
    inline Parameter<int16_t> EPS_MCU_TEMP_BIAS(0);
    inline Parameter<int16_t> EPS_MCU_TEMP_PREMUL(0);
    inline Parameter<int16_t> EPS_MCU_TEMP_POSDIV(0);
    inline Parameter<int16_t> EPS_BP1_TEMP1_BIAS(0);
    inline Parameter<int16_t> EPS_BP1_TEMP2_BIAS(0);
    inline Parameter<int16_t> EPS_BP1_TEMP3_BIAS(0);
    inline Parameter<int16_t> EPS_BP2_TEMP1_BIAS(0);
    inline Parameter<int16_t> EPS_BP2_TEMP2_BIAS(0);
    inline Parameter<int16_t> EPS_BP2_TEMP3_BIAS(0);
    inline Parameter<int16_t> EPS_BP3_TEMP1_BIAS(0);
    inline Parameter<int16_t> EPS_BP3_TEMP2_BIAS(0);
    inline Parameter<int16_t> EPS_BP3_TEMP3_BIAS(0);
    inline Parameter<int16_t> EPS_BP1_TEMP1_PREMUL(0);
    inline Parameter<int16_t> EPS_BP1_TEMP2_PREMUL(0);
    inline Parameter<int16_t> EPS_BP1_TEMP3_PREMUL(0);
    inline Parameter<int16_t> EPS_BP2_TEMP1_PREMUL(0);
    inline Parameter<int16_t> EPS_BP2_TEMP2_PREMUL(0);
    inline Parameter<int16_t> EPS_BP2_TEMP3_PREMUL(0);
    inline Parameter<int16_t> EPS_BP3_TEMP1_PREMUL(0);
    inline Parameter<int16_t> EPS_BP3_TEMP2_PREMUL(0);
    inline Parameter<int16_t> EPS_BP3_TEMP3_PREMUL(0);
    inline Parameter<int16_t> EPS_BP1_TEMP1_POSDIV(0);
    inline Parameter<int16_t> EPS_BP1_TEMP2_POSDIV(0);
    inline Parameter<int16_t> EPS_BP1_TEMP3_POSDIV(0);
    inline Parameter<int16_t> EPS_BP2_TEMP1_POSDIV(0);
    inline Parameter<int16_t> EPS_BP2_TEMP2_POSDIV(0);
    inline Parameter<int16_t> EPS_BP2_TEMP3_POSDIV(0);
    inline Parameter<int16_t> EPS_BP3_TEMP1_POSDIV(0);
    inline Parameter<int16_t> EPS_BP3_TEMP2_POSDIV(0);
    inline Parameter<int16_t> EPS_BP3_TEMP3_POSDIV(0);
    inline Parameter<uint8_t> EPS_BOARD_IDENTIFIER(0);
    inline Parameter<uint8_t> EPS_BOARD_IDENTIFIER_KEY(0);
    inline Parameter<uint8_t> EPS_RAVG_STRENGTH_P2(0);
    inline Parameter<int8_t> EPS_AUTO_HEAT_ENA_BP1(0);
    inline Parameter<int8_t> EPS_AUTO_HEAT_ENA_BP2(0);
    inline Parameter<int8_t> EPS_AUTO_HEAT_ENA_BP3(0);
    inline Parameter<int8_t> EPS_AUTO_BAL_ENA_BP1(0);
    inline Parameter<int8_t> EPS_AUTO_BAL_ENA_BP2(0);
    inline Parameter<int8_t> EPS_AUTO_BAL_ENA_BP3(0);
    inline Parameter<int8_t> EPS_VD1_ALWAYS_ENA(0);
    inline Parameter<int8_t> EPS_VD1_ALWAYS_DISA(0);
    inline Parameter<uint32_t> EPS_CH_FORCE_ENA_USE_BF(0);
    inline Parameter<uint32_t> EPS_CH_STARTUP_ENA_USE_BF(0);
    inline Parameter<uint32_t> EPS_CH_LATCHOFF_ENA_USE_BF(0);
    inline Parameter<uint32_t> EPS_VD1_ALLOC_CH_BF(0);
    inline Parameter<uint32_t> EPS_SWCI_CH_CMD_ENA_BF(0);
    inline Parameter<uint32_t> EPS_SWCI_CH_CMD_DISA_BF(0);
    inline Parameter<uint16_t> EPS_TTC_I2C_SLAVE_ADDR(0);
    inline Parameter<uint16_t> EPS_CONF_NVM_SAVE_CNTR(0);
    inline Parameter<uint16_t> EPS_CONF_NVM_SAVE_CHKS(0);
    inline Parameter<uint16_t> EPS_RST_CAUSE(0);
    inline Parameter<uint16_t> EPS_RST_CNTR_PWRON(0);
    inline Parameter<uint16_t> EPS_RST_CNTR_WDG(0);
    inline Parameter<uint16_t> EPS_RST_CNTR_CMD(0);
    inline Parameter<uint16_t> EPS_RST_CNTR_MCU(0);
    inline Parameter<uint16_t> EPS_RST_CNTR_EMLOPO(0);
    inline Parameter<uint16_t> EPS_RST_CODE_MCU_RAW(0);
    inline Parameter<uint16_t> EPS_EMLOPO_VOLT_LOTHR(0);
    inline Parameter<uint16_t> EPS_EMLOPO_VOLT_HITHR(0);
    inline Parameter<uint16_t> EPS_EMLOPO_PERIOD(0);
    inline Parameter<uint16_t> EPS_SAFETY_VOLT_LOTHR_USED(0);
    inline Parameter<uint16_t> EPS_SAFETY_VOLT_HITHR_USED(0);
    inline Parameter<uint16_t> EPS_SAFETY_LINGER(0);
    inline Parameter<uint16_t> EPS_TTC_WDG_TIMOUT_USED(0);
    inline Parameter<uint16_t> EPS_TTC_PREVCMD_ELAPSED(0);
    inline Parameter<uint8_t> EPS_STID(0);
    inline Parameter<uint8_t> EPS_IVID(0);
    inline Parameter<uint8_t> EPS_BID_USED(0);
    inline Parameter<uint8_t> EPS_BOOT_RESUME_SHORT(0);
    inline Parameter<int8_t> EPS_CONF_PARAM_CHANGED(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_INPUT_RAW(0);
    inline Parameter<uint16_t> EPS_VIP_CC1_OUTPUT_VOLT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC1_OUTPUT_CURR_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC1_OUTPUT_POWE_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_VOLT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_CURR_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_POWE_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_VOLT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_CURR_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_POWE_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_VOLT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_CURR_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_POWE_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_VOLT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_CURR_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_POWE_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CC1_OUTPUT_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC1_OUTPUT_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC1_OUTPUT_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_CC1_OUTPUT_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC1_OUTPUT_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC1_OUTPUT_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC2_OUTPUT_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC3_OUTPUT_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC4_OUTPUT_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_CC5_OUTPUT_POWE_RA(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_DIST_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_DIST_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_DIST_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_VOLT_BAT_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_CURR_BAT_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_POWE_BAT_INPUT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_VOLT_RAW(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_CURR_RAW(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_POWE_RAW(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_VOLT_ENG(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_CURR_ENG(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_POWE_ENG(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_VOLT_RA(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_CURR_RA(0);
    inline Parameter<int16_t> EPS_VIP_OUTPUT_POWE_RA(0);
    inline Parameter<int16_t> EPS_ADC_MCU_TEMP_V25T30(0);
    inline Parameter<int16_t> EPS_ADC_MCU_TEMP_V25T85(0);
} // namespace EPSParameters
#pragma GCC diagnostic pop