#include "ECSS_Configuration.hpp"

#ifdef SERVICE_PARAMETER

#include "Services/ParameterService.hpp"
#include "PlatformParameters.hpp"

void ParameterService::initializeParameterMap() {
    parameters = {{PeakSatParameters::OBCMCUTemperature, PeakSatParameters::obcMCUTemperature},
                  {PeakSatParameters::OBCUseRTT, PeakSatParameters::obcUseRTT},
                  {PeakSatParameters::OBCUseUART, PeakSatParameters::obcUseUART},
                  {PeakSatParameters::OBCUseCAN, PeakSatParameters::obcUseCAN},
                  //-----------------------------------------------------------------------------------------------
                  {PeakSatParameters::OBCPCBTemperature1, PeakSatParameters::obcPCBTemperature1},
                  {PeakSatParameters::OBCPCBTemperature2, PeakSatParameters::obcPCBTemperature2},
                  {PeakSatParameters::OBCMCUInputVoltage, PeakSatParameters::obcMCUInputVoltage},
                  {PeakSatParameters::OBCMCUBootCounter, PeakSatParameters::obcMCUBootCounter},
                  {PeakSatParameters::OBCFlashInt, PeakSatParameters::obcFlashInt},
                  {PeakSatParameters::OBCSRAMInt, PeakSatParameters::obcSRAMInt},
                  {PeakSatParameters::OBCAvailableMRAM, PeakSatParameters::obcAvailableMRAM},
                  {PeakSatParameters::OBCAvailableNAND, PeakSatParameters::obcAvailableNAND},
                  {PeakSatParameters::OBCSpacecraftTimeRef, PeakSatParameters::obcSpacecraftTimeRef},
                  {PeakSatParameters::OBCOnBoardTime, PeakSatParameters::obcOnBoardTime},
                  {PeakSatParameters::OBCOperationalMode, PeakSatParameters::obcOperationalMode},
                  {PeakSatParameters::OBCMemoryPartition, PeakSatParameters::obcMemoryPartition},
                  {PeakSatParameters::OBCReconfigurationTimer, PeakSatParameters::obcReconfigurationTimer},
                  {PeakSatParameters::OBCLastFailedEvent, PeakSatParameters::obcLastFailedEvent},
                  {PeakSatParameters::OBCMCUSystick, PeakSatParameters::obcMCUSystick},
                  {PeakSatParameters::OBCCANBUSLoad1, PeakSatParameters::obcCANBUSLoad1},
                  {PeakSatParameters::OBCCANBUSLoad2, PeakSatParameters::obcCANBUSLoad2},

                  {PeakSatParameters::OBCMCUFDIR, PeakSatParameters::obcMCUFDIR},
                  {PeakSatParameters::OBCMCURestartSafeModeThreshold, PeakSatParameters::obcMCURestartSafeModeThreshold},
                  {PeakSatParameters::OBCNANDFLASHLCLThreshold, PeakSatParameters::obcNANDFLASHLCLThreshold},
                  {PeakSatParameters::OBCMRAMLCLThreshold, PeakSatParameters::obcMRAMLCLThreshold},
                  {PeakSatParameters::OBCNANDFLASHON, PeakSatParameters::obcNANDFLASHON},
                  {PeakSatParameters::OBCMRAMON, PeakSatParameters::obcNANDFlashScrubbingFrequency},
                  {PeakSatParameters::OBCNANDFLASHScrubbingFrequency, PeakSatParameters::obcMRAMON},
                  {PeakSatParameters::OBCRAMScrubbingFrequency, PeakSatParameters::obcRAMScrubbingFrequency},
                  {PeakSatParameters::OBCProgramFlashScrubbingFrequency, PeakSatParameters::obcProgramFlashScrubbingFrequency},
                  //---------------------------------------------------------------------------------------------
                  {PeakSatParameters::EPS_MODE,    PeakSatParameters::epsMODE},
                  {PeakSatParameters::EPS_CONF,    PeakSatParameters::epsCONF},
                  {PeakSatParameters::EPS_RESET_CAUSE,PeakSatParameters::epsRESET_CAUSE},
                  {PeakSatParameters::EPS_UPTIME,  PeakSatParameters::epsUPTIME},
                  {PeakSatParameters::EPS_ERROR,   PeakSatParameters::epsERROR},
                  {PeakSatParameters::EPS_RC_CNT_PWRON,PeakSatParameters::epsRC_CNT_PWRON},
                  {PeakSatParameters::EPS_RC_CNT_WDG,PeakSatParameters::epsRC_CNT_WDG},
                  {PeakSatParameters::EPS_RC_CNT_CMD,PeakSatParameters::epsRC_CNT_CMD},
                  {PeakSatParameters::EPS_RC_CNT_MCU,PeakSatParameters::epsRC_CNT_MCU},
                  {PeakSatParameters::EPS_RC_CNT_EMLOPO,PeakSatParameters::epsRC_CNT_EMLOPO},
                  {PeakSatParameters::EPS_PREVCMD_ELAPSED,PeakSatParameters::epsPREVCMD_ELAPSED},
                  {PeakSatParameters::EPS_UNIX_TIME,PeakSatParameters::epsUNIX_TIME},
                  {PeakSatParameters::EPS_UNIX_YEAR,PeakSatParameters::epsUNIX_YEAR},
                  {PeakSatParameters::EPS_UNIX_MONTH,PeakSatParameters::epsUNIX_MONTH},
                  {PeakSatParameters::EPS_UNIX_DAY,PeakSatParameters::epsUNIX_DAY},
                  {PeakSatParameters::EPS_UNIX_HOUR,PeakSatParameters::epsUNIX_HOUR},
                  {PeakSatParameters::EPS_UNIX_MINUTE,PeakSatParameters::epsUNIX_MINUTE},
                  {PeakSatParameters::EPS_UNIX_SECOND,PeakSatParameters::epsUNIX_SECOND},
                  {PeakSatParameters::EPS_STAT_CH_ON,PeakSatParameters::epsSTAT_CH_ON},
                  {PeakSatParameters::EPS_STAT_CH_EXT_ON,PeakSatParameters::epsSTAT_CH_EXT_ON},
                  {PeakSatParameters::EPS_STAT_CH_OCF,PeakSatParameters::epsSTAT_CH_OCF},
                  {PeakSatParameters::EPS_STAT_CH_EXT_OCF,PeakSatParameters::epsSTAT_CH_EXT_OCF},
                  {PeakSatParameters::EPS_OCF_CNT_CH00,PeakSatParameters::epsOCF_CNT_CH00},
                  {PeakSatParameters::EPS_OCF_CNT_CH01,PeakSatParameters::epsOCF_CNT_CH01},
                  {PeakSatParameters::EPS_OCF_CNT_CH02,PeakSatParameters::epsOCF_CNT_CH02},
                  {PeakSatParameters::EPS_OCF_CNT_CH03,PeakSatParameters::epsOCF_CNT_CH03},
                  {PeakSatParameters::EPS_OCF_CNT_CH04,PeakSatParameters::epsOCF_CNT_CH04},
                  {PeakSatParameters::EPS_OCF_CNT_CH05,PeakSatParameters::epsOCF_CNT_CH05},
                  {PeakSatParameters::EPS_OCF_CNT_CH06,PeakSatParameters::epsOCF_CNT_CH06},
                  {PeakSatParameters::EPS_OCF_CNT_CH07,PeakSatParameters::epsOCF_CNT_CH07},
                  {PeakSatParameters::EPS_OCF_CNT_CH08,PeakSatParameters::epsOCF_CNT_CH08},
                  {PeakSatParameters::EPS_OCF_CNT_CH09,PeakSatParameters::epsOCF_CNT_CH09},
                  {PeakSatParameters::EPS_OCF_CNT_CH10,PeakSatParameters::epsOCF_CNT_CH10},
                  {PeakSatParameters::EPS_OCF_CNT_CH11,PeakSatParameters::epsOCF_CNT_CH11},
                  {PeakSatParameters::EPS_OCF_CNT_CH12,PeakSatParameters::epsOCF_CNT_CH12},
                  {PeakSatParameters::EPS_OCF_CNT_CH13,PeakSatParameters::epsOCF_CNT_CH13},
                  {PeakSatParameters::EPS_OCF_CNT_CH14,PeakSatParameters::epsOCF_CNT_CH14},
                  {PeakSatParameters::EPS_OCF_CNT_CH15,PeakSatParameters::epsOCF_CNT_CH15},
                  {PeakSatParameters::EPS_ABF_PLACED_0,PeakSatParameters::epsABF_PLACED_0},
                  {PeakSatParameters::EPS_ABF_PLACED_1,PeakSatParameters::epsABF_PLACED_1},
                  {PeakSatParameters::EPS_VOLT_BRDSUP_RAW,PeakSatParameters::epsVOLT_BRDSUP_RAW},
                  {PeakSatParameters::EPS_TEMP_MCU_RAW,PeakSatParameters::epsTEMP_MCU_RAW},
                  {PeakSatParameters::EPS_VIP_VOLT_VD0_RAW,PeakSatParameters::epsVIP_VOLT_VD0_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_VD0_RAW,PeakSatParameters::epsVIP_CURR_VD0_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_VD0_RAW,PeakSatParameters::epsVIP_POWE_VD0_RAW},
                  {PeakSatParameters::EPS_VIP_VOLT_VD1_RAW,PeakSatParameters::epsVIP_VOLT_VD1_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_VD1_RAW,PeakSatParameters::epsVIP_CURR_VD1_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_VD1_RAW,PeakSatParameters::epsVIP_POWE_VD1_RAW},
                  {PeakSatParameters::EPS_VIP_VOLT_VD2_RAW,PeakSatParameters::epsVIP_VOLT_VD2_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_VD2_RAW,PeakSatParameters::epsVIP_CURR_VD2_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_VD2_RAW,PeakSatParameters::epsVIP_POWE_VD2_RAW},
                  {PeakSatParameters::EPS_VIP_VOLT_VD3_RAW,PeakSatParameters::epsVIP_VOLT_VD3_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_VD3_RAW,PeakSatParameters::epsVIP_CURR_VD3_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_VD3_RAW,PeakSatParameters::epsVIP_POWE_VD3_RAW},
                  {PeakSatParameters::EPS_VIP_VOLT_VD4_RAW,PeakSatParameters::epsVIP_VOLT_VD4_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_VD4_RAW,PeakSatParameters::epsVIP_CURR_VD4_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_VD4_RAW,PeakSatParameters::epsVIP_POWE_VD4_RAW},
                  {PeakSatParameters::EPS_VIP_VOLT_VD5_RAW,PeakSatParameters::epsVIP_VOLT_VD5_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_VD5_RAW,PeakSatParameters::epsVIP_CURR_VD5_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_VD5_RAW,PeakSatParameters::epsVIP_POWE_VD5_RAW},
                  {PeakSatParameters::EPS_VIP_VOLT_VD6_RAW,PeakSatParameters::epsVIP_VOLT_VD6_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_VD6_RAW,PeakSatParameters::epsVIP_CURR_VD6_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_VD6_RAW,PeakSatParameters::epsVIP_POWE_VD6_RAW},
                  {PeakSatParameters::EPS_VOLT_BRDSUP_ENG,PeakSatParameters::epsVOLT_BRDSUP_ENG},
                  {PeakSatParameters::EPS_TEMP_MCU_ENG,PeakSatParameters::epsTEMP_MCU_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_INPUT_ENG,PeakSatParameters::epsVIP_VOLT_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_INPUT_ENG,PeakSatParameters::epsVIP_CURR_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_INPUT_ENG,PeakSatParameters::epsVIP_POWE_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_DIST_INPUT_ENG,PeakSatParameters::epsVIP_VOLT_DIST_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_DIST_INPUT_ENG,PeakSatParameters::epsVIP_CURR_DIST_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_DIST_INPUT_ENG,PeakSatParameters::epsVIP_POWE_DIST_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_BAT_INPUT_ENG,PeakSatParameters::epsVIP_VOLT_BAT_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_BAT_INPUT_ENG,PeakSatParameters::epsVIP_CURR_BAT_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_BAT_INPUT_ENG,PeakSatParameters::epsVIP_POWE_BAT_INPUT_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_VD0_ENG,PeakSatParameters::epsVIP_VOLT_VD0_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_VD0_ENG,PeakSatParameters::epsVIP_CURR_VD0_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_VD0_ENG,PeakSatParameters::epsVIP_POWE_VD0_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_VD1_ENG,PeakSatParameters::epsVIP_VOLT_VD1_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_VD1_ENG,PeakSatParameters::epsVIP_CURR_VD1_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_VD1_ENG,PeakSatParameters::epsVIP_POWE_VD1_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_VD2_ENG,PeakSatParameters::epsVIP_VOLT_VD2_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_VD2_ENG,PeakSatParameters::epsVIP_CURR_VD2_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_VD2_ENG,PeakSatParameters::epsVIP_POWE_VD2_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_VD3_ENG,PeakSatParameters::epsVIP_VOLT_VD3_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_VD3_ENG,PeakSatParameters::epsVIP_CURR_VD3_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_VD3_ENG,PeakSatParameters::epsVIP_POWE_VD3_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_VD4_ENG,PeakSatParameters::epsVIP_VOLT_VD4_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_VD4_ENG,PeakSatParameters::epsVIP_CURR_VD4_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_VD4_ENG,PeakSatParameters::epsVIP_POWE_VD4_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_VD5_ENG,PeakSatParameters::epsVIP_VOLT_VD5_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_VD5_ENG,PeakSatParameters::epsVIP_CURR_VD5_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_VD5_ENG,PeakSatParameters::epsVIP_POWE_VD5_ENG},
                  {PeakSatParameters::EPS_VIP_VOLT_VD6_ENG,PeakSatParameters::epsVIP_VOLT_VD6_ENG},
                  {PeakSatParameters::EPS_VIP_CURR_VD6_ENG,PeakSatParameters::epsVIP_CURR_VD6_ENG},
                  {PeakSatParameters::EPS_VIP_POWE_VD6_ENG,PeakSatParameters::epsVIP_POWE_VD6_ENG},
                  {PeakSatParameters::EPS_VOLT_BRDSUP_RA,PeakSatParameters::epsVOLT_BRDSUP_RA},
                  {PeakSatParameters::EPS_TEMP_MCU_RA,PeakSatParameters::epsTEMP_MCU_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_INPUT_RA,PeakSatParameters::epsVIP_VOLT_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_CURR_INPUT_RA,PeakSatParameters::epsVIP_CURR_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_POWE_INPUT_RA,PeakSatParameters::epsVIP_POWE_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_DIST_INPUT_RA,PeakSatParameters::epsVIP_VOLT_DIST_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_CURR_DIST_INPUT_RA,PeakSatParameters::epsVIP_CURR_DIST_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_POWE_DIST_INPUT_RA,PeakSatParameters::epsVIP_POWE_DIST_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_BAT_INPUT_RA,PeakSatParameters::epsVIP_VOLT_BAT_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_CURR_BAT_INPUT_RA,PeakSatParameters::epsVIP_CURR_BAT_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_POWE_BAT_INPUT_RA,PeakSatParameters::epsVIP_POWE_BAT_INPUT_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_VD0_RA,PeakSatParameters::epsVIP_VOLT_VD0_RA},
                  {PeakSatParameters::EPS_VIP_CURR_VD0_RA,PeakSatParameters::epsVIP_CURR_VD0_RA},
                  {PeakSatParameters::EPS_VIP_POWE_VD0_RA,PeakSatParameters::epsVIP_POWE_VD0_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_VD1_RA,PeakSatParameters::epsVIP_VOLT_VD1_RA},
                  {PeakSatParameters::EPS_VIP_CURR_VD1_RA,PeakSatParameters::epsVIP_CURR_VD1_RA},
                  {PeakSatParameters::EPS_VIP_POWE_VD1_RA,PeakSatParameters::epsVIP_POWE_VD1_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_VD2_RA,PeakSatParameters::epsVIP_VOLT_VD2_RA},
                  {PeakSatParameters::EPS_VIP_CURR_VD2_RA,PeakSatParameters::epsVIP_CURR_VD2_RA},
                  {PeakSatParameters::EPS_VIP_POWE_VD2_RA,PeakSatParameters::epsVIP_POWE_VD2_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_VD3_RA,PeakSatParameters::epsVIP_VOLT_VD3_RA},
                  {PeakSatParameters::EPS_VIP_CURR_VD3_RA,PeakSatParameters::epsVIP_CURR_VD3_RA},
                  {PeakSatParameters::EPS_VIP_POWE_VD3_RA,PeakSatParameters::epsVIP_POWE_VD3_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_VD4_RA,PeakSatParameters::epsVIP_VOLT_VD4_RA},
                  {PeakSatParameters::EPS_VIP_CURR_VD4_RA,PeakSatParameters::epsVIP_CURR_VD4_RA},
                  {PeakSatParameters::EPS_VIP_POWE_VD4_RA,PeakSatParameters::epsVIP_POWE_VD4_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_VD5_RA,PeakSatParameters::epsVIP_VOLT_VD5_RA},
                  {PeakSatParameters::EPS_VIP_CURR_VD5_RA,PeakSatParameters::epsVIP_CURR_VD5_RA},
                  {PeakSatParameters::EPS_VIP_POWE_VD5_RA,PeakSatParameters::epsVIP_POWE_VD5_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_VD6_RA,PeakSatParameters::epsVIP_VOLT_VD6_RA},
                  {PeakSatParameters::EPS_VIP_CURR_VD6_RA,PeakSatParameters::epsVIP_CURR_VD6_RA},
                  {PeakSatParameters::EPS_VIP_POWE_VD6_RA,PeakSatParameters::epsVIP_POWE_VD6_RA},
                  {PeakSatParameters::EPS_VIP_CH00_VOLT_RAW, PeakSatParameters::epsVIP_CH00_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH00_CURR_RAW, PeakSatParameters::epsVIP_CH00_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH00_POWE_RAW, PeakSatParameters::epsVIP_CH00_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH01_VOLT_RAW, PeakSatParameters::epsVIP_CH01_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH01_CURR_RAW, PeakSatParameters::epsVIP_CH01_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH01_POWE_RAW, PeakSatParameters::epsVIP_CH01_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH02_VOLT_RAW, PeakSatParameters::epsVIP_CH02_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH02_CURR_RAW, PeakSatParameters::epsVIP_CH02_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH02_POWE_RAW, PeakSatParameters::epsVIP_CH02_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH03_VOLT_RAW, PeakSatParameters::epsVIP_CH03_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH03_CURR_RAW, PeakSatParameters::epsVIP_CH03_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH03_POWE_RAW, PeakSatParameters::epsVIP_CH03_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH04_VOLT_RAW, PeakSatParameters::epsVIP_CH04_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH04_CURR_RAW, PeakSatParameters::epsVIP_CH04_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH04_POWE_RAW, PeakSatParameters::epsVIP_CH04_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH05_VOLT_RAW, PeakSatParameters::epsVIP_CH05_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH05_CURR_RAW, PeakSatParameters::epsVIP_CH05_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH05_POWE_RAW, PeakSatParameters::epsVIP_CH05_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH06_VOLT_RAW, PeakSatParameters::epsVIP_CH06_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH06_CURR_RAW, PeakSatParameters::epsVIP_CH06_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH06_POWE_RAW, PeakSatParameters::epsVIP_CH06_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH07_VOLT_RAW, PeakSatParameters::epsVIP_CH07_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH07_CURR_RAW, PeakSatParameters::epsVIP_CH07_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH07_POWE_RAW, PeakSatParameters::epsVIP_CH07_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH08_VOLT_RAW, PeakSatParameters::epsVIP_CH08_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH08_CURR_RAW, PeakSatParameters::epsVIP_CH08_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH08_POWE_RAW, PeakSatParameters::epsVIP_CH08_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH09_VOLT_RAW, PeakSatParameters::epsVIP_CH09_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH09_CURR_RAW, PeakSatParameters::epsVIP_CH09_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH09_POWE_RAW, PeakSatParameters::epsVIP_CH09_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH10_VOLT_RAW, PeakSatParameters::epsVIP_CH10_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH10_CURR_RAW, PeakSatParameters::epsVIP_CH10_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH10_POWE_RAW, PeakSatParameters::epsVIP_CH10_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH11_VOLT_RAW, PeakSatParameters::epsVIP_CH11_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH11_CURR_RAW, PeakSatParameters::epsVIP_CH11_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH11_POWE_RAW, PeakSatParameters::epsVIP_CH11_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH12_VOLT_RAW, PeakSatParameters::epsVIP_CH12_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH12_CURR_RAW, PeakSatParameters::epsVIP_CH12_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH12_POWE_RAW, PeakSatParameters::epsVIP_CH12_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH13_VOLT_RAW, PeakSatParameters::epsVIP_CH13_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH13_CURR_RAW, PeakSatParameters::epsVIP_CH13_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH13_POWE_RAW, PeakSatParameters::epsVIP_CH13_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH14_VOLT_RAW, PeakSatParameters::epsVIP_CH14_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CH14_CURR_RAW, PeakSatParameters::epsVIP_CH14_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CH14_POWE_RAW, PeakSatParameters::epsVIP_CH14_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CH00_VOLT_ENG, PeakSatParameters::epsVIP_CH00_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH00_CURR_ENG, PeakSatParameters::epsVIP_CH00_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH00_POWE_ENG, PeakSatParameters::epsVIP_CH00_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH01_VOLT_ENG, PeakSatParameters::epsVIP_CH01_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH01_CURR_ENG, PeakSatParameters::epsVIP_CH01_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH01_POWE_ENG, PeakSatParameters::epsVIP_CH01_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH02_VOLT_ENG, PeakSatParameters::epsVIP_CH02_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH02_CURR_ENG, PeakSatParameters::epsVIP_CH02_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH02_POWE_ENG, PeakSatParameters::epsVIP_CH02_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH03_VOLT_ENG, PeakSatParameters::epsVIP_CH03_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH03_CURR_ENG, PeakSatParameters::epsVIP_CH03_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH03_POWE_ENG, PeakSatParameters::epsVIP_CH03_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH04_VOLT_ENG, PeakSatParameters::epsVIP_CH04_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH04_CURR_ENG, PeakSatParameters::epsVIP_CH04_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH04_POWE_ENG, PeakSatParameters::epsVIP_CH04_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH05_VOLT_ENG, PeakSatParameters::epsVIP_CH05_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH05_CURR_ENG, PeakSatParameters::epsVIP_CH05_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH05_POWE_ENG, PeakSatParameters::epsVIP_CH05_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH06_VOLT_ENG, PeakSatParameters::epsVIP_CH06_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH06_CURR_ENG, PeakSatParameters::epsVIP_CH06_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH06_POWE_ENG, PeakSatParameters::epsVIP_CH06_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH07_VOLT_ENG, PeakSatParameters::epsVIP_CH07_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH07_CURR_ENG, PeakSatParameters::epsVIP_CH07_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH07_POWE_ENG, PeakSatParameters::epsVIP_CH07_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH08_VOLT_ENG, PeakSatParameters::epsVIP_CH08_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH08_CURR_ENG, PeakSatParameters::epsVIP_CH08_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH08_POWE_ENG, PeakSatParameters::epsVIP_CH08_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH09_VOLT_ENG, PeakSatParameters::epsVIP_CH09_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH09_CURR_ENG, PeakSatParameters::epsVIP_CH09_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH09_POWE_ENG, PeakSatParameters::epsVIP_CH09_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH10_VOLT_ENG, PeakSatParameters::epsVIP_CH10_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH10_CURR_ENG, PeakSatParameters::epsVIP_CH10_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH10_POWE_ENG, PeakSatParameters::epsVIP_CH10_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH11_VOLT_ENG, PeakSatParameters::epsVIP_CH11_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH11_CURR_ENG, PeakSatParameters::epsVIP_CH11_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH11_POWE_ENG, PeakSatParameters::epsVIP_CH11_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH12_VOLT_ENG, PeakSatParameters::epsVIP_CH12_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH12_CURR_ENG, PeakSatParameters::epsVIP_CH12_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH12_POWE_ENG, PeakSatParameters::epsVIP_CH12_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH13_VOLT_ENG, PeakSatParameters::epsVIP_CH13_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH13_CURR_ENG, PeakSatParameters::epsVIP_CH13_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH13_POWE_ENG, PeakSatParameters::epsVIP_CH13_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH14_VOLT_ENG, PeakSatParameters::epsVIP_CH14_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CH14_CURR_ENG, PeakSatParameters::epsVIP_CH14_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CH14_POWE_ENG, PeakSatParameters::epsVIP_CH14_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CH00_VOLT_RA, PeakSatParameters::epsVIP_CH00_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH00_CURR_RA, PeakSatParameters::epsVIP_CH00_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH00_POWE_RA, PeakSatParameters::epsVIP_CH00_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH01_VOLT_RA, PeakSatParameters::epsVIP_CH01_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH01_CURR_RA, PeakSatParameters::epsVIP_CH01_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH01_POWE_RA, PeakSatParameters::epsVIP_CH01_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH02_VOLT_RA, PeakSatParameters::epsVIP_CH02_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH02_CURR_RA, PeakSatParameters::epsVIP_CH02_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH02_POWE_RA, PeakSatParameters::epsVIP_CH02_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH03_VOLT_RA, PeakSatParameters::epsVIP_CH03_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH03_CURR_RA, PeakSatParameters::epsVIP_CH03_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH03_POWE_RA, PeakSatParameters::epsVIP_CH03_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH04_VOLT_RA, PeakSatParameters::epsVIP_CH04_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH04_CURR_RA, PeakSatParameters::epsVIP_CH04_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH04_POWE_RA, PeakSatParameters::epsVIP_CH04_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH05_VOLT_RA, PeakSatParameters::epsVIP_CH05_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH05_CURR_RA, PeakSatParameters::epsVIP_CH05_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH05_POWE_RA, PeakSatParameters::epsVIP_CH05_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH06_VOLT_RA, PeakSatParameters::epsVIP_CH06_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH06_CURR_RA, PeakSatParameters::epsVIP_CH06_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH06_POWE_RA, PeakSatParameters::epsVIP_CH06_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH07_VOLT_RA, PeakSatParameters::epsVIP_CH07_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH07_CURR_RA, PeakSatParameters::epsVIP_CH07_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH07_POWE_RA, PeakSatParameters::epsVIP_CH07_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH08_VOLT_RA, PeakSatParameters::epsVIP_CH08_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH08_CURR_RA, PeakSatParameters::epsVIP_CH08_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH08_POWE_RA, PeakSatParameters::epsVIP_CH08_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH09_VOLT_RA, PeakSatParameters::epsVIP_CH09_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH09_CURR_RA, PeakSatParameters::epsVIP_CH09_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH09_POWE_RA, PeakSatParameters::epsVIP_CH09_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH10_VOLT_RA, PeakSatParameters::epsVIP_CH10_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH10_CURR_RA, PeakSatParameters::epsVIP_CH10_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH10_POWE_RA, PeakSatParameters::epsVIP_CH10_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH11_VOLT_RA, PeakSatParameters::epsVIP_CH11_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH11_CURR_RA, PeakSatParameters::epsVIP_CH11_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH11_POWE_RA, PeakSatParameters::epsVIP_CH11_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH12_VOLT_RA, PeakSatParameters::epsVIP_CH12_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH12_CURR_RA, PeakSatParameters::epsVIP_CH12_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH12_POWE_RA, PeakSatParameters::epsVIP_CH12_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH13_VOLT_RA, PeakSatParameters::epsVIP_CH13_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH13_CURR_RA, PeakSatParameters::epsVIP_CH13_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH13_POWE_RA, PeakSatParameters::epsVIP_CH13_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CH14_VOLT_RA, PeakSatParameters::epsVIP_CH14_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CH14_CURR_RA, PeakSatParameters::epsVIP_CH14_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CH14_POWE_RA, PeakSatParameters::epsVIP_CH14_POWE_RA},
                  {PeakSatParameters::EPS_STAT_BU, PeakSatParameters::epsSTAT_BU},
                  {PeakSatParameters::EPS_VOLT_BP1_INPUT_RAW,PeakSatParameters::epsVOLT_BP1_INPUT_RAW},
                  {PeakSatParameters::EPS_CURR_BP1_INPUT_RAW,PeakSatParameters::epsCURR_BP1_INPUT_RAW},
                  {PeakSatParameters::EPS_POWE_BP1_INPUT_RAW,PeakSatParameters::epsPOWE_BP1_INPUT_RAW},
                  {PeakSatParameters::EPS_STAT_BP1_RAW,PeakSatParameters::epsSTAT_BP1_RAW},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL1_RAW,PeakSatParameters::epsVOLT_BP1_CELL1_RAW},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL2_RAW,PeakSatParameters::epsVOLT_BP1_CELL2_RAW},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL3_RAW,PeakSatParameters::epsVOLT_BP1_CELL3_RAW},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL4_RAW,PeakSatParameters::epsVOLT_BP1_CELL4_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP1_RAW,PeakSatParameters::epsBAT_TEMP1_BP1_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP1_RAW,PeakSatParameters::epsBAT_TEMP2_BP1_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP1_RAW,PeakSatParameters::epsBAT_TEMP3_BP1_RAW},
                  {PeakSatParameters::EPS_VOLT_BP2_INPUT_RAW,PeakSatParameters::epsVOLT_BP2_INPUT_RAW},
                  {PeakSatParameters::EPS_CURR_BP2_INPUT_RAW,PeakSatParameters::epsCURR_BP2_INPUT_RAW},
                  {PeakSatParameters::EPS_POWE_BP2_INPUT_RAW,PeakSatParameters::epsPOWE_BP2_INPUT_RAW},
                  {PeakSatParameters::EPS_STAT_BP2_RAW,PeakSatParameters::epsSTAT_BP2_RAW},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL1_RAW,PeakSatParameters::epsVOLT_BP2_CELL1_RAW},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL2_RAW,PeakSatParameters::epsVOLT_BP2_CELL2_RAW},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL3_RAW,PeakSatParameters::epsVOLT_BP2_CELL3_RAW},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL4_RAW,PeakSatParameters::epsVOLT_BP2_CELL4_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP2_RAW,PeakSatParameters::epsBAT_TEMP1_BP2_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP2_RAW,PeakSatParameters::epsBAT_TEMP2_BP2_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP2_RAW,PeakSatParameters::epsBAT_TEMP3_BP2_RAW},
                  {PeakSatParameters::EPS_VOLT_BP3_INPUT_RAW,PeakSatParameters::epsVOLT_BP3_INPUT_RAW},
                  {PeakSatParameters::EPS_CURR_BP3_INPUT_RAW,PeakSatParameters::epsCURR_BP3_INPUT_RAW},
                  {PeakSatParameters::EPS_POWE_BP3_INPUT_RAW,PeakSatParameters::epsPOWE_BP3_INPUT_RAW},
                  {PeakSatParameters::EPS_STAT_BP3_RAW,PeakSatParameters::epsSTAT_BP3_RAW},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL1_RAW,PeakSatParameters::epsVOLT_BP3_CELL1_RAW},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL2_RAW,PeakSatParameters::epsVOLT_BP3_CELL2_RAW},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL3_RAW,PeakSatParameters::epsVOLT_BP3_CELL3_RAW},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL4_RAW,PeakSatParameters::epsVOLT_BP3_CELL4_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP3_RAW,PeakSatParameters::epsBAT_TEMP1_BP3_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP3_RAW,PeakSatParameters::epsBAT_TEMP2_BP3_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP3_RAW,PeakSatParameters::epsBAT_TEMP3_BP3_RAW},
                  {PeakSatParameters::EPS_VOLT_BP1_INPUT_ENG,PeakSatParameters::epsVOLT_BP1_INPUT_ENG},
                  {PeakSatParameters::EPS_CURR_BP1_INPUT_ENG,PeakSatParameters::epsCURR_BP1_INPUT_ENG},
                  {PeakSatParameters::EPS_POWE_BP1_INPUT_ENG,PeakSatParameters::epsPOWE_BP1_INPUT_ENG},
                  {PeakSatParameters::EPS_STAT_BP1_ENG,PeakSatParameters::epsSTAT_BP1_ENG},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL1_ENG,PeakSatParameters::epsVOLT_BP1_CELL1_ENG},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL2_ENG,PeakSatParameters::epsVOLT_BP1_CELL2_ENG},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL3_ENG,PeakSatParameters::epsVOLT_BP1_CELL3_ENG},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL4_ENG,PeakSatParameters::epsVOLT_BP1_CELL4_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP1_ENG,PeakSatParameters::epsBAT_TEMP1_BP1_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP1_ENG,PeakSatParameters::epsBAT_TEMP2_BP1_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP1_ENG,PeakSatParameters::epsBAT_TEMP3_BP1_ENG},
                  {PeakSatParameters::EPS_VOLT_BP2_INPUT_ENG,PeakSatParameters::epsVOLT_BP2_INPUT_ENG},
                  {PeakSatParameters::EPS_CURR_BP2_INPUT_ENG,PeakSatParameters::epsCURR_BP2_INPUT_ENG},
                  {PeakSatParameters::EPS_POWE_BP2_INPUT_ENG,PeakSatParameters::epsPOWE_BP2_INPUT_ENG},
                  {PeakSatParameters::EPS_STAT_BP2_ENG,PeakSatParameters::epsSTAT_BP2_ENG},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL1_ENG,PeakSatParameters::epsVOLT_BP2_CELL1_ENG},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL2_ENG,PeakSatParameters::epsVOLT_BP2_CELL2_ENG},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL3_ENG,PeakSatParameters::epsVOLT_BP2_CELL3_ENG},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL4_ENG,PeakSatParameters::epsVOLT_BP2_CELL4_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP2_ENG,PeakSatParameters::epsBAT_TEMP1_BP2_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP2_ENG,PeakSatParameters::epsBAT_TEMP2_BP2_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP2_ENG,PeakSatParameters::epsBAT_TEMP3_BP2_ENG},
                  {PeakSatParameters::EPS_VOLT_BP3_INPUT_ENG,PeakSatParameters::epsVOLT_BP3_INPUT_ENG},
                  {PeakSatParameters::EPS_CURR_BP3_INPUT_ENG,PeakSatParameters::epsCURR_BP3_INPUT_ENG},
                  {PeakSatParameters::EPS_POWE_BP3_INPUT_ENG,PeakSatParameters::epsPOWE_BP3_INPUT_ENG},
                  {PeakSatParameters::EPS_STAT_BP3_ENG,PeakSatParameters::epsSTAT_BP3_ENG},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL1_ENG,PeakSatParameters::epsVOLT_BP3_CELL1_ENG},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL2_ENG,PeakSatParameters::epsVOLT_BP3_CELL2_ENG},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL3_ENG,PeakSatParameters::epsVOLT_BP3_CELL3_ENG},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL4_ENG,PeakSatParameters::epsVOLT_BP3_CELL4_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP3_ENG,PeakSatParameters::epsBAT_TEMP1_BP3_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP3_ENG,PeakSatParameters::epsBAT_TEMP2_BP3_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP3_ENG,PeakSatParameters::epsBAT_TEMP3_BP3_ENG},
                  {PeakSatParameters::EPS_VOLT_BP1_INPUT_RA,PeakSatParameters::epsVOLT_BP1_INPUT_RA},
                  {PeakSatParameters::EPS_CURR_BP1_INPUT_RA,PeakSatParameters::epsCURR_BP1_INPUT_RA},
                  {PeakSatParameters::EPS_POWE_BP1_INPUT_RA,PeakSatParameters::epsPOWE_BP1_INPUT_RA},
                  {PeakSatParameters::EPS_STAT_BP1_RA,PeakSatParameters::epsSTAT_BP1_RA},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL1_RA,PeakSatParameters::epsVOLT_BP1_CELL1_RA},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL2_RA,PeakSatParameters::epsVOLT_BP1_CELL2_RA},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL3_RA,PeakSatParameters::epsVOLT_BP1_CELL3_RA},
                  {PeakSatParameters::EPS_VOLT_BP1_CELL4_RA,PeakSatParameters::epsVOLT_BP1_CELL4_RA},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP1_RA,PeakSatParameters::epsBAT_TEMP1_BP1_RA},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP1_RA,PeakSatParameters::epsBAT_TEMP2_BP1_RA},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP1_RA,PeakSatParameters::epsBAT_TEMP3_BP1_RA},
                  {PeakSatParameters::EPS_VOLT_BP2_INPUT_RA,PeakSatParameters::epsVOLT_BP2_INPUT_RA},
                  {PeakSatParameters::EPS_CURR_BP2_INPUT_RA,PeakSatParameters::epsCURR_BP2_INPUT_RA},
                  {PeakSatParameters::EPS_POWE_BP2_INPUT_RA,PeakSatParameters::epsPOWE_BP2_INPUT_RA},
                  {PeakSatParameters::EPS_STAT_BP2_RA,PeakSatParameters::epsSTAT_BP2_RA},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL1_RA,PeakSatParameters::epsVOLT_BP2_CELL1_RA},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL2_RA,PeakSatParameters::epsVOLT_BP2_CELL2_RA},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL3_RA,PeakSatParameters::epsVOLT_BP2_CELL3_RA},
                  {PeakSatParameters::EPS_VOLT_BP2_CELL4_RA,PeakSatParameters::epsVOLT_BP2_CELL4_RA},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP2_RA,PeakSatParameters::epsBAT_TEMP1_BP2_RA},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP2_RA,PeakSatParameters::epsBAT_TEMP2_BP2_RA},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP2_RA,PeakSatParameters::epsBAT_TEMP3_BP2_RA},
                  {PeakSatParameters::EPS_VOLT_BP3_INPUT_RA,PeakSatParameters::epsVOLT_BP3_INPUT_RA},
                  {PeakSatParameters::EPS_CURR_BP3_INPUT_RA,PeakSatParameters::epsCURR_BP3_INPUT_RA},
                  {PeakSatParameters::EPS_POWE_BP3_INPUT_RA,PeakSatParameters::epsPOWE_BP3_INPUT_RA},
                  {PeakSatParameters::EPS_STAT_BP3_RA,PeakSatParameters::epsSTAT_BP3_RA},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL1_RA,PeakSatParameters::epsVOLT_BP3_CELL1_RA},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL2_RA,PeakSatParameters::epsVOLT_BP3_CELL2_RA},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL3_RA,PeakSatParameters::epsVOLT_BP3_CELL3_RA},
                  {PeakSatParameters::EPS_VOLT_BP3_CELL4_RA,PeakSatParameters::epsVOLT_BP3_CELL4_RA},
                  {PeakSatParameters::EPS_BAT_TEMP1_BP3_RA,PeakSatParameters::epsBAT_TEMP1_BP3_RA},
                  {PeakSatParameters::EPS_BAT_TEMP2_BP3_RA,PeakSatParameters::epsBAT_TEMP2_BP3_RA},
                  {PeakSatParameters::EPS_BAT_TEMP3_BP3_RA,PeakSatParameters::epsBAT_TEMP3_BP3_RA},
                  {PeakSatParameters::EPS_VOLT_VD0_RAW,PeakSatParameters::epsVOLT_VD0_RAW},
                  {PeakSatParameters::EPS_VOLT_VD1_RAW,PeakSatParameters::epsVOLT_VD1_RAW},
                  {PeakSatParameters::EPS_VOLT_VD2_RAW,PeakSatParameters::epsVOLT_VD2_RAW},
                  {PeakSatParameters::EPS_VOLT_VD0_ENG,PeakSatParameters::epsVOLT_VD0_ENG},
                  {PeakSatParameters::EPS_VOLT_VD1_ENG,PeakSatParameters::epsVOLT_VD1_ENG},
                  {PeakSatParameters::EPS_VOLT_VD2_ENG,PeakSatParameters::epsVOLT_VD2_ENG},
                  {PeakSatParameters::EPS_VOLT_VD0_RA,PeakSatParameters::epsVOLT_VD0_RA},
                  {PeakSatParameters::EPS_VOLT_VD1_RA,PeakSatParameters::epsVOLT_VD1_RA},
                  {PeakSatParameters::EPS_VOLT_VD2_RA,PeakSatParameters::epsVOLT_VD2_RA},
                  {PeakSatParameters::EPS_BAT_STAT,PeakSatParameters::epsBAT_STAT},
                  {PeakSatParameters::EPS_BAT_TEMP2_RAW,PeakSatParameters::epsBAT_TEMP2_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP3_RAW,PeakSatParameters::epsBAT_TEMP3_RAW},
                  {PeakSatParameters::EPS_BAT_TEMP2_ENG,PeakSatParameters::epsBAT_TEMP2_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP3_ENG,PeakSatParameters::epsBAT_TEMP3_ENG},
                  {PeakSatParameters::EPS_BAT_TEMP2_RA,PeakSatParameters::epsBAT_TEMP2_RA},
                  {PeakSatParameters::EPS_BAT_TEMP3_RA,PeakSatParameters::epsBAT_TEMP3_RA},
                  {PeakSatParameters::EPS_CC1_VOLT_IN_MPPT_RAW,PeakSatParameters::epsCC1_VOLT_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC2_VOLT_IN_MPPT_RAW,PeakSatParameters::epsCC2_VOLT_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC3_VOLT_IN_MPPT_RAW,PeakSatParameters::epsCC3_VOLT_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC4_VOLT_IN_MPPT_RAW,PeakSatParameters::epsCC4_VOLT_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC5_VOLT_IN_MPPT_RAW,PeakSatParameters::epsCC5_VOLT_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC1_CURR_IN_MPPT_RAW,PeakSatParameters::epsCC1_CURR_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC2_CURR_IN_MPPT_RAW,PeakSatParameters::epsCC2_CURR_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC3_CURR_IN_MPPT_RAW,PeakSatParameters::epsCC3_CURR_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC4_CURR_IN_MPPT_RAW,PeakSatParameters::epsCC4_CURR_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC5_CURR_IN_MPPT_RAW,PeakSatParameters::epsCC5_CURR_IN_MPPT_RAW},
                  {PeakSatParameters::EPS_CC1_VOLT_OU_MPPT_RAW,PeakSatParameters::epsCC1_VOLT_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC2_VOLT_OU_MPPT_RAW,PeakSatParameters::epsCC2_VOLT_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC3_VOLT_OU_MPPT_RAW,PeakSatParameters::epsCC3_VOLT_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC4_VOLT_OU_MPPT_RAW,PeakSatParameters::epsCC4_VOLT_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC5_VOLT_OU_MPPT_RAW,PeakSatParameters::epsCC5_VOLT_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC1_CURR_OU_MPPT_RAW,PeakSatParameters::epsCC1_CURR_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC2_CURR_OU_MPPT_RAW,PeakSatParameters::epsCC2_CURR_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC3_CURR_OU_MPPT_RAW,PeakSatParameters::epsCC3_CURR_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC4_CURR_OU_MPPT_RAW,PeakSatParameters::epsCC4_CURR_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC5_CURR_OU_MPPT_RAW,PeakSatParameters::epsCC5_CURR_OU_MPPT_RAW},
                  {PeakSatParameters::EPS_CC1_VOLT_IN_MPPT_ENG,PeakSatParameters::epsCC1_VOLT_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC2_VOLT_IN_MPPT_ENG,PeakSatParameters::epsCC2_VOLT_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC3_VOLT_IN_MPPT_ENG,PeakSatParameters::epsCC3_VOLT_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC4_VOLT_IN_MPPT_ENG,PeakSatParameters::epsCC4_VOLT_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC5_VOLT_IN_MPPT_ENG,PeakSatParameters::epsCC5_VOLT_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC1_CURR_IN_MPPT_ENG,PeakSatParameters::epsCC1_CURR_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC2_CURR_IN_MPPT_ENG,PeakSatParameters::epsCC2_CURR_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC3_CURR_IN_MPPT_ENG,PeakSatParameters::epsCC3_CURR_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC4_CURR_IN_MPPT_ENG,PeakSatParameters::epsCC4_CURR_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC5_CURR_IN_MPPT_ENG,PeakSatParameters::epsCC5_CURR_IN_MPPT_ENG},
                  {PeakSatParameters::EPS_CC1_VOLT_OU_MPPT_ENG,PeakSatParameters::epsCC1_VOLT_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC2_VOLT_OU_MPPT_ENG,PeakSatParameters::epsCC2_VOLT_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC3_VOLT_OU_MPPT_ENG,PeakSatParameters::epsCC3_VOLT_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC4_VOLT_OU_MPPT_ENG,PeakSatParameters::epsCC4_VOLT_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC5_VOLT_OU_MPPT_ENG,PeakSatParameters::epsCC5_VOLT_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC1_CURR_OU_MPPT_ENG,PeakSatParameters::epsCC1_CURR_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC2_CURR_OU_MPPT_ENG,PeakSatParameters::epsCC2_CURR_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC3_CURR_OU_MPPT_ENG,PeakSatParameters::epsCC3_CURR_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC4_CURR_OU_MPPT_ENG,PeakSatParameters::epsCC4_CURR_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC5_CURR_OU_MPPT_ENG,PeakSatParameters::epsCC5_CURR_OU_MPPT_ENG},
                  {PeakSatParameters::EPS_CC1_VOLT_IN_MPPT_RA,PeakSatParameters::epsCC1_VOLT_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC2_VOLT_IN_MPPT_RA,PeakSatParameters::epsCC2_VOLT_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC3_VOLT_IN_MPPT_RA,PeakSatParameters::epsCC3_VOLT_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC4_VOLT_IN_MPPT_RA,PeakSatParameters::epsCC4_VOLT_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC5_VOLT_IN_MPPT_RA,PeakSatParameters::epsCC5_VOLT_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC1_CURR_IN_MPPT_RA,PeakSatParameters::epsCC1_CURR_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC2_CURR_IN_MPPT_RA,PeakSatParameters::epsCC2_CURR_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC3_CURR_IN_MPPT_RA,PeakSatParameters::epsCC3_CURR_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC4_CURR_IN_MPPT_RA,PeakSatParameters::epsCC4_CURR_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC5_CURR_IN_MPPT_RA,PeakSatParameters::epsCC5_CURR_IN_MPPT_RA},
                  {PeakSatParameters::EPS_CC1_VOLT_OU_MPPT_RA,PeakSatParameters::epsCC1_VOLT_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC2_VOLT_OU_MPPT_RA,PeakSatParameters::epsCC2_VOLT_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC3_VOLT_OU_MPPT_RA,PeakSatParameters::epsCC3_VOLT_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC4_VOLT_OU_MPPT_RA,PeakSatParameters::epsCC4_VOLT_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC5_VOLT_OU_MPPT_RA,PeakSatParameters::epsCC5_VOLT_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC1_CURR_OU_MPPT_RA,PeakSatParameters::epsCC1_CURR_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC2_CURR_OU_MPPT_RA,PeakSatParameters::epsCC2_CURR_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC3_CURR_OU_MPPT_RA,PeakSatParameters::epsCC3_CURR_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC4_CURR_OU_MPPT_RA,PeakSatParameters::epsCC4_CURR_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CC5_CURR_OU_MPPT_RA,PeakSatParameters::epsCC5_CURR_OU_MPPT_RA},
                  {PeakSatParameters::EPS_CH_STARTUP_ENA_BF,PeakSatParameters::epsCH_STARTUP_ENA_BF},
                  {PeakSatParameters::EPS_CH_STARTUP_KEY,PeakSatParameters::epsCH_STARTUP_KEY},
                  {PeakSatParameters::EPS_CH_LATCHOFF_ENA_BF,PeakSatParameters::epsCH_LATCHOFF_ENA_BF},
                  {PeakSatParameters::EPS_CH_LATCHOFF_KEY,PeakSatParameters::epsCH_LATCHOFF_KEY},
                  {PeakSatParameters::EPS_TTC_WDG_TIMEOUT,PeakSatParameters::epsTTC_WDG_TIMEOUT},
                  {PeakSatParameters::EPS_TTC_WDG_TIMEOUT_KEY,PeakSatParameters::epsTTC_WDG_TIMEOUT_KEY},
                  {PeakSatParameters::EPS_CH_STARTUP_DELAY_CH1,PeakSatParameters::epsCH_STARTUP_DELAY_CH1},
                  {PeakSatParameters::EPS_CH_LATCHOFF_DELAY_CH1,PeakSatParameters::epsCH_LATCHOFF_DELAY_CH1},
                  {PeakSatParameters::EPS_SAFETY_VOLT_LOTHR,PeakSatParameters::epsSAFETY_VOLT_LOTHR},
                  {PeakSatParameters::EPS_SAFETY_VOLT_HITHR,PeakSatParameters::epsSAFETY_VOLT_HITHR},
                  {PeakSatParameters::EPS_LOTHR_BP1_HEATER,PeakSatParameters::epsLOTHR_BP1_HEATER},
                  {PeakSatParameters::EPS_LOTHR_BP2_HEATER,PeakSatParameters::epsLOTHR_BP2_HEATER},
                  {PeakSatParameters::EPS_LOTHR_BP3_HEATER,PeakSatParameters::epsLOTHR_BP3_HEATER},
                  {PeakSatParameters::EPS_HITHR_BP1_HEATER,PeakSatParameters::epsHITHR_BP1_HEATER},
                  {PeakSatParameters::EPS_HITHR_BP2_HEATER,PeakSatParameters::epsHITHR_BP2_HEATER},
                  {PeakSatParameters::EPS_HITHR_BP3_HEATER,PeakSatParameters::epsHITHR_BP3_HEATER},
                  {PeakSatParameters::EPS_LOTHR_BP1_UNBAL,PeakSatParameters::epsLOTHR_BP1_UNBAL},
                  {PeakSatParameters::EPS_LOTHR_BP2_UNBAL,PeakSatParameters::epsLOTHR_BP2_UNBAL},
                  {PeakSatParameters::EPS_LOTHR_BP3_UNBAL,PeakSatParameters::epsLOTHR_BP3_UNBAL},
                  {PeakSatParameters::EPS_HITHR_BP1_UNBAL,PeakSatParameters::epsHITHR_BP1_UNBAL},
                  {PeakSatParameters::EPS_HITHR_BP2_UNBAL,PeakSatParameters::epsHITHR_BP2_UNBAL},
                  {PeakSatParameters::EPS_HITHR_BP3_UNBAL,PeakSatParameters::epsHITHR_BP3_UNBAL},
                  {PeakSatParameters::EPS_MCU_TEMP_BIAS,PeakSatParameters::epsMCU_TEMP_BIAS},
                  {PeakSatParameters::EPS_MCU_TEMP_PREMUL,PeakSatParameters::epsMCU_TEMP_PREMUL},
                  {PeakSatParameters::EPS_MCU_TEMP_POSDIV,PeakSatParameters::epsMCU_TEMP_POSDIV},
                  {PeakSatParameters::EPS_BP1_TEMP1_BIAS,PeakSatParameters::epsBP1_TEMP1_BIAS},
                  {PeakSatParameters::EPS_BP1_TEMP2_BIAS,PeakSatParameters::epsBP1_TEMP2_BIAS},
                  {PeakSatParameters::EPS_BP1_TEMP3_BIAS,PeakSatParameters::epsBP1_TEMP3_BIAS},
                  {PeakSatParameters::EPS_BP2_TEMP1_BIAS,PeakSatParameters::epsBP2_TEMP1_BIAS},
                  {PeakSatParameters::EPS_BP2_TEMP2_BIAS,PeakSatParameters::epsBP2_TEMP2_BIAS},
                  {PeakSatParameters::EPS_BP2_TEMP3_BIAS,PeakSatParameters::epsBP2_TEMP3_BIAS},
                  {PeakSatParameters::EPS_BP3_TEMP1_BIAS,PeakSatParameters::epsBP3_TEMP1_BIAS},
                  {PeakSatParameters::EPS_BP3_TEMP2_BIAS,PeakSatParameters::epsBP3_TEMP2_BIAS},
                  {PeakSatParameters::EPS_BP3_TEMP3_BIAS,PeakSatParameters::epsBP3_TEMP3_BIAS},
                  {PeakSatParameters::EPS_BP1_TEMP1_PREMUL,PeakSatParameters::epsBP1_TEMP1_PREMUL},
                  {PeakSatParameters::EPS_BP1_TEMP2_PREMUL,PeakSatParameters::epsBP1_TEMP2_PREMUL},
                  {PeakSatParameters::EPS_BP1_TEMP3_PREMUL,PeakSatParameters::epsBP1_TEMP3_PREMUL},
                  {PeakSatParameters::EPS_BP2_TEMP1_PREMUL,PeakSatParameters::epsBP2_TEMP1_PREMUL},
                  {PeakSatParameters::EPS_BP2_TEMP2_PREMUL,PeakSatParameters::epsBP2_TEMP2_PREMUL},
                  {PeakSatParameters::EPS_BP2_TEMP3_PREMUL,PeakSatParameters::epsBP2_TEMP3_PREMUL},
                  {PeakSatParameters::EPS_BP3_TEMP1_PREMUL,PeakSatParameters::epsBP3_TEMP1_PREMUL},
                  {PeakSatParameters::EPS_BP3_TEMP2_PREMUL,PeakSatParameters::epsBP3_TEMP2_PREMUL},
                  {PeakSatParameters::EPS_BP3_TEMP3_PREMUL,PeakSatParameters::epsBP3_TEMP3_PREMUL},
                  {PeakSatParameters::EPS_BP1_TEMP1_POSDIV,PeakSatParameters::epsBP1_TEMP1_POSDIV},
                  {PeakSatParameters::EPS_BP1_TEMP2_POSDIV,PeakSatParameters::epsBP1_TEMP2_POSDIV},
                  {PeakSatParameters::EPS_BP1_TEMP3_POSDIV,PeakSatParameters::epsBP1_TEMP3_POSDIV},
                  {PeakSatParameters::EPS_BP2_TEMP1_POSDIV,PeakSatParameters::epsBP2_TEMP1_POSDIV},
                  {PeakSatParameters::EPS_BP2_TEMP2_POSDIV,PeakSatParameters::epsBP2_TEMP2_POSDIV},
                  {PeakSatParameters::EPS_BP2_TEMP3_POSDIV,PeakSatParameters::epsBP2_TEMP3_POSDIV},
                  {PeakSatParameters::EPS_BP3_TEMP1_POSDIV,PeakSatParameters::epsBP3_TEMP1_POSDIV},
                  {PeakSatParameters::EPS_BP3_TEMP2_POSDIV,PeakSatParameters::epsBP3_TEMP2_POSDIV},
                  {PeakSatParameters::EPS_BP3_TEMP3_POSDIV,PeakSatParameters::epsBP3_TEMP3_POSDIV},
                  {PeakSatParameters::EPS_BOARD_IDENTIFIER,PeakSatParameters::epsBOARD_IDENTIFIER},
                  {PeakSatParameters::EPS_BOARD_IDENTIFIER_KEY,PeakSatParameters::epsBOARD_IDENTIFIER_KEY},
                  {PeakSatParameters::EPS_RAVG_STRENGTH_P2,PeakSatParameters::epsRAVG_STRENGTH_P2},
                  {PeakSatParameters::EPS_AUTO_HEAT_ENA_BP1,PeakSatParameters::epsAUTO_HEAT_ENA_BP1},
                  {PeakSatParameters::EPS_AUTO_HEAT_ENA_BP2,PeakSatParameters::epsAUTO_HEAT_ENA_BP2},
                  {PeakSatParameters::EPS_AUTO_HEAT_ENA_BP3,PeakSatParameters::epsAUTO_HEAT_ENA_BP3},
                  {PeakSatParameters::EPS_AUTO_BAL_ENA_BP1,PeakSatParameters::epsAUTO_BAL_ENA_BP1},
                  {PeakSatParameters::EPS_AUTO_BAL_ENA_BP2,PeakSatParameters::epsAUTO_BAL_ENA_BP2},
                  {PeakSatParameters::EPS_AUTO_BAL_ENA_BP3,PeakSatParameters::epsAUTO_BAL_ENA_BP3},
                  {PeakSatParameters::EPS_VD1_ALWAYS_ENA,PeakSatParameters::epsVD1_ALWAYS_ENA},
                  {PeakSatParameters::EPS_VD1_ALWAYS_DISA,PeakSatParameters::epsVD1_ALWAYS_DISA},
                  {PeakSatParameters::EPS_CH_FORCE_ENA_USE_BF,PeakSatParameters::epsCH_FORCE_ENA_USE_BF},
                  {PeakSatParameters::EPS_CH_STARTUP_ENA_USE_BF,PeakSatParameters::epsCH_STARTUP_ENA_USE_BF},
                  {PeakSatParameters::EPS_CH_LATCHOFF_ENA_USE_BF,PeakSatParameters::epsCH_LATCHOFF_ENA_USE_BF},
                  {PeakSatParameters::EPS_VD1_ALLOC_CH_BF,PeakSatParameters::epsVD1_ALLOC_CH_BF},
                  {PeakSatParameters::EPS_SWCI_CH_CMD_ENA_BF,PeakSatParameters::epsSWCI_CH_CMD_ENA_BF},
                  {PeakSatParameters::EPS_SWCI_CH_CMD_DISA_BF,PeakSatParameters::epsSWCI_CH_CMD_DISA_BF},
                  {PeakSatParameters::EPS_TTC_I2C_SLAVE_ADDR,PeakSatParameters::epsTTC_I2C_SLAVE_ADDR},
                  {PeakSatParameters::EPS_CONF_NVM_SAVE_CNTR,PeakSatParameters::epsCONF_NVM_SAVE_CNTR},
                  {PeakSatParameters::EPS_CONF_NVM_SAVE_CHKS,PeakSatParameters::epsCONF_NVM_SAVE_CHKS},
                  {PeakSatParameters::EPS_RST_CAUSE,PeakSatParameters::epsRST_CAUSE},
                  {PeakSatParameters::EPS_RST_CNTR_PWRON,PeakSatParameters::epsRST_CNTR_PWRON},
                  {PeakSatParameters::EPS_RST_CNTR_WDG,PeakSatParameters::epsRST_CNTR_WDG},
                  {PeakSatParameters::EPS_RST_CNTR_CMD,PeakSatParameters::epsRST_CNTR_CMD},
                  {PeakSatParameters::EPS_RST_CNTR_MCU,PeakSatParameters::epsRST_CNTR_MCU},
                  {PeakSatParameters::EPS_RST_CNTR_EMLOPO,PeakSatParameters::epsRST_CNTR_EMLOPO},
                  {PeakSatParameters::EPS_RST_CODE_MCU_RAW,PeakSatParameters::epsRST_CODE_MCU_RAW},
                  {PeakSatParameters::EPS_EMLOPO_VOLT_LOTHR,PeakSatParameters::epsEMLOPO_VOLT_LOTHR},
                  {PeakSatParameters::EPS_EMLOPO_VOLT_HITHR,PeakSatParameters::epsEMLOPO_VOLT_HITHR},
                  {PeakSatParameters::EPS_EMLOPO_PERIOD,PeakSatParameters::epsEMLOPO_PERIOD},
                  {PeakSatParameters::EPS_SAFETY_VOLT_LOTHR_USED,PeakSatParameters::epsSAFETY_VOLT_LOTHR_USED},
                  {PeakSatParameters::EPS_SAFETY_VOLT_HITHR_USED,PeakSatParameters::epsSAFETY_VOLT_HITHR_USED},
                  {PeakSatParameters::EPS_SAFETY_LINGER,PeakSatParameters::epsSAFETY_LINGER},
                  {PeakSatParameters::EPS_TTC_WDG_TIMOUT_USED,PeakSatParameters::epsTTC_WDG_TIMOUT_USED},
                  {PeakSatParameters::EPS_TTC_PREVCMD_ELAPSED,PeakSatParameters::epsTTC_PREVCMD_ELAPSED},
                  {PeakSatParameters::EPS_STID,    PeakSatParameters::epsSTID},
                  {PeakSatParameters::EPS_IVID,    PeakSatParameters::epsIVID},
                  {PeakSatParameters::EPS_BID_USED,PeakSatParameters::epsBID_USED},
                  {PeakSatParameters::EPS_BOOT_RESUME_SHORT,PeakSatParameters::epsBOOT_RESUME_SHORT},
                  {PeakSatParameters::EPS_CONF_PARAM_CHANGED,PeakSatParameters::epsCONF_PARAM_CHANGED},
                  {PeakSatParameters::EPS_VIP_VOLT_INPUT_RAW, PeakSatParameters::epsVIP_VOLT_INPUT_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_INPUT_RAW, PeakSatParameters::epsVIP_CURR_INPUT_RAW},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_VOLT_RAW, PeakSatParameters::epsVIP_CC1_OUTPUT_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_CURR_RAW, PeakSatParameters::epsVIP_CC1_OUTPUT_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_POWE_RAW, PeakSatParameters::epsVIP_CC1_OUTPUT_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_VOLT_RAW, PeakSatParameters::epsVIP_CC2_OUTPUT_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_CURR_RAW, PeakSatParameters::epsVIP_CC2_OUTPUT_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_POWE_RAW, PeakSatParameters::epsVIP_CC2_OUTPUT_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_VOLT_RAW, PeakSatParameters::epsVIP_CC3_OUTPUT_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_CURR_RAW, PeakSatParameters::epsVIP_CC3_OUTPUT_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_POWE_RAW, PeakSatParameters::epsVIP_CC3_OUTPUT_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_VOLT_RAW, PeakSatParameters::epsVIP_CC4_OUTPUT_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_CURR_RAW, PeakSatParameters::epsVIP_CC4_OUTPUT_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_POWE_RAW, PeakSatParameters::epsVIP_CC4_OUTPUT_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_VOLT_RAW, PeakSatParameters::epsVIP_CC5_OUTPUT_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_CURR_RAW, PeakSatParameters::epsVIP_CC5_OUTPUT_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_POWE_RAW, PeakSatParameters::epsVIP_CC5_OUTPUT_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_VOLT_ENG, PeakSatParameters::epsVIP_CC1_OUTPUT_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_CURR_ENG, PeakSatParameters::epsVIP_CC1_OUTPUT_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_POWE_ENG, PeakSatParameters::epsVIP_CC1_OUTPUT_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_VOLT_ENG, PeakSatParameters::epsVIP_CC2_OUTPUT_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_CURR_ENG, PeakSatParameters::epsVIP_CC2_OUTPUT_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_POWE_ENG, PeakSatParameters::epsVIP_CC2_OUTPUT_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_VOLT_ENG, PeakSatParameters::epsVIP_CC3_OUTPUT_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_CURR_ENG, PeakSatParameters::epsVIP_CC3_OUTPUT_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_POWE_ENG, PeakSatParameters::epsVIP_CC3_OUTPUT_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_VOLT_ENG, PeakSatParameters::epsVIP_CC4_OUTPUT_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_CURR_ENG, PeakSatParameters::epsVIP_CC4_OUTPUT_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_POWE_ENG, PeakSatParameters::epsVIP_CC4_OUTPUT_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_VOLT_ENG, PeakSatParameters::epsVIP_CC5_OUTPUT_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_CURR_ENG, PeakSatParameters::epsVIP_CC5_OUTPUT_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_POWE_ENG, PeakSatParameters::epsVIP_CC5_OUTPUT_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_VOLT_RA, PeakSatParameters::epsVIP_CC1_OUTPUT_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_CURR_RA, PeakSatParameters::epsVIP_CC1_OUTPUT_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CC1_OUTPUT_POWE_RA, PeakSatParameters::epsVIP_CC1_OUTPUT_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_VOLT_RA, PeakSatParameters::epsVIP_CC2_OUTPUT_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_CURR_RA, PeakSatParameters::epsVIP_CC2_OUTPUT_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CC2_OUTPUT_POWE_RA, PeakSatParameters::epsVIP_CC2_OUTPUT_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_VOLT_RA, PeakSatParameters::epsVIP_CC3_OUTPUT_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_CURR_RA, PeakSatParameters::epsVIP_CC3_OUTPUT_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CC3_OUTPUT_POWE_RA, PeakSatParameters::epsVIP_CC3_OUTPUT_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_VOLT_RA, PeakSatParameters::epsVIP_CC4_OUTPUT_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_CURR_RA, PeakSatParameters::epsVIP_CC4_OUTPUT_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CC4_OUTPUT_POWE_RA, PeakSatParameters::epsVIP_CC4_OUTPUT_POWE_RA},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_VOLT_RA, PeakSatParameters::epsVIP_CC5_OUTPUT_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_CURR_RA, PeakSatParameters::epsVIP_CC5_OUTPUT_CURR_RA},
                  {PeakSatParameters::EPS_VIP_CC5_OUTPUT_POWE_RA, PeakSatParameters::epsVIP_CC5_OUTPUT_POWE_RA},
                  {PeakSatParameters::EPS_VIP_VOLT_DIST_INPUT_RAW, PeakSatParameters::epsVIP_VOLT_DIST_INPUT_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_DIST_INPUT_RAW, PeakSatParameters::epsVIP_CURR_DIST_INPUT_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_DIST_INPUT_RAW, PeakSatParameters::epsVIP_POWE_DIST_INPUT_RAW},
                  {PeakSatParameters::EPS_VIP_VOLT_BAT_INPUT_RAW, PeakSatParameters::epsVIP_VOLT_BAT_INPUT_RAW},
                  {PeakSatParameters::EPS_VIP_CURR_BAT_INPUT_RAW, PeakSatParameters::epsVIP_CURR_BAT_INPUT_RAW},
                  {PeakSatParameters::EPS_VIP_POWE_BAT_INPUT_RAW, PeakSatParameters::epsVIP_POWE_BAT_INPUT_RAW},
                  {PeakSatParameters::EPS_VIP_OUTPUT_VOLT_RAW, PeakSatParameters::epsVIP_OUTPUT_VOLT_RAW},
                  {PeakSatParameters::EPS_VIP_OUTPUT_CURR_RAW, PeakSatParameters::epsVIP_OUTPUT_CURR_RAW},
                  {PeakSatParameters::EPS_VIP_OUTPUT_POWE_RAW, PeakSatParameters::epsVIP_OUTPUT_POWE_RAW},
                  {PeakSatParameters::EPS_VIP_OUTPUT_VOLT_ENG, PeakSatParameters::epsVIP_OUTPUT_VOLT_ENG},
                  {PeakSatParameters::EPS_VIP_OUTPUT_CURR_ENG, PeakSatParameters::epsVIP_OUTPUT_CURR_ENG},
                  {PeakSatParameters::EPS_VIP_OUTPUT_POWE_ENG, PeakSatParameters::epsVIP_OUTPUT_POWE_ENG},
                  {PeakSatParameters::EPS_VIP_OUTPUT_VOLT_RA , PeakSatParameters::epsVIP_OUTPUT_VOLT_RA},
                  {PeakSatParameters::EPS_VIP_OUTPUT_CURR_RA , PeakSatParameters::epsVIP_OUTPUT_CURR_RA},
                  {PeakSatParameters::EPS_VIP_OUTPUT_POWE_RA , PeakSatParameters::epsVIP_OUTPUT_POWE_RA},
                  {PeakSatParameters::EPS_ADC_MCU_TEMP_V25T30 , PeakSatParameters::epsADC_MCU_TEMP_V25T30},
                  {PeakSatParameters::EPS_ADC_MCU_TEMP_V25T85 , PeakSatParameters::epsADC_MCU_TEMP_V25T85},

                  //---------------------------------------------------------------------------------------------
                  {PeakSatParameters::COMMS_UHFBandPATemperatureID, PeakSatParameters::commsUHFBandPATemperature},
                  {PeakSatParameters::COMMS_PCBTemperatureID, PeakSatParameters::commsPCBTemperature},
                  {PeakSatParameters::COMMS_GNSSTemperatureID, PeakSatParameters::commsGNSSTemperature},
                  {PeakSatParameters::Antenna_Deployment_StatusID, PeakSatParameters::Antenna_Deployment_Status},

                 //---------------------------------------------------------------------------------------------
                  {PeakSatParameters::PAY_xID, PeakSatParameters::pay_x},
                  {PeakSatParameters::PAY_yID, PeakSatParameters::pay_y},
                  {PeakSatParameters::PAY_zID, PeakSatParameters::pay_z},
                  {PeakSatParameters::PAY_uptimeID, PeakSatParameters::pay_uptime},
                  {PeakSatParameters::PAY_timeID, PeakSatParameters::pay_time},
                  {PeakSatParameters::PAY_psu_12vID, PeakSatParameters::pay_psu_12v},
                  {PeakSatParameters::PAY_psu_5vID, PeakSatParameters::pay_psu_5v},
                  {PeakSatParameters::PAY_psu_33vID, PeakSatParameters::pay_psu_33v},
                  {PeakSatParameters::PAY_mcu_die_temperatureID, PeakSatParameters::pay_mcu_die_temperature},
                  {PeakSatParameters::PAY_main_board_temperatureID, PeakSatParameters::pay_main_board_temperature},
                  {PeakSatParameters::PAY_seed_ld_output_powerID, PeakSatParameters::pay_seed_ld_output_power},
                  {PeakSatParameters::PAY_fsm_chamber_temperatureID, PeakSatParameters::pay_fsm_chamber_temperature},
                  {PeakSatParameters::PAY_fsm_chamber_pressureID, PeakSatParameters::pay_fsm_chamber_pressure},
                  {PeakSatParameters::PAY_fsmd_voltage_converter_temperatureID, PeakSatParameters::pay_fsmd_voltage_converter_temperature},
                  {PeakSatParameters::PAY_fsmd_drivers_temperatureID, PeakSatParameters::pay_fsmd_drivers_temperature},
                  {PeakSatParameters::PAY_camera_pcb_temperatureID, PeakSatParameters::pay_camera_pcb_temperature},
                  {PeakSatParameters::PAY_camera_sensor_temperatureID, PeakSatParameters::pay_camera_sensor_temperature},
                  {PeakSatParameters::PAY_fso_aux_temperature_1ID, PeakSatParameters::pay_fso_aux_temperature_1},
                  {PeakSatParameters::PAY_fso_aux_temperature_2ID, PeakSatParameters::pay_fso_aux_temperature_2},
                  {PeakSatParameters::PAY_oad_temperatureID, PeakSatParameters::pay_oad_temperature},
                  {PeakSatParameters::PAY_optical_amplifier_combiner_heater_temperatureID, PeakSatParameters::pay_optical_amplifier_combiner_heater_temperature},
                  {PeakSatParameters::PAY_optical_amplifier_fiber_mirror_temperatureID, PeakSatParameters::pay_optical_amplifier_fiber_mirror_temperature},
                  {PeakSatParameters::PAY_optical_amplifier_circulator_heater_temperatureID, PeakSatParameters::pay_optical_amplifier_circulator_heater_temperature},
                  {PeakSatParameters::PAY_ldd_temperatureID, PeakSatParameters::pay_ldd_temperature},
                  {PeakSatParameters::PAY_ld_temperatureID, PeakSatParameters::pay_ld_temperature},
                  {PeakSatParameters::PAY_ldd_12v_currentID, PeakSatParameters::pay_ldd_12v_current},
                  {PeakSatParameters::PAY_ldd_psu_12vID, PeakSatParameters::pay_ldd_psu_12v},
                  {PeakSatParameters::PAY_ldd_converter_input_currentID, PeakSatParameters::pay_ldd_converter_input_current},
                  {PeakSatParameters::PAY_ldd_ld_vID, PeakSatParameters::pay_ldd_ld_v},
                  {PeakSatParameters::PAY_ldd_ld_dac_set_vID, PeakSatParameters::pay_ldd_ld_dac_set_v},
                  {PeakSatParameters::PAY_fsm_driver_12v_currentID, PeakSatParameters::pay_fsm_driver_12v_current},
                  {PeakSatParameters::PAY_flashes_33v_currentID, PeakSatParameters::pay_flashes_33v_current},
                  {PeakSatParameters::PAY_fpga_5v_currentID, PeakSatParameters::pay_fpga_5v_current},
                  {PeakSatParameters::PAY_sdd_33v_currentID, PeakSatParameters::pay_sdd_33v_current},
                  {PeakSatParameters::PAY_pump_ld_powerID, PeakSatParameters::pay_pump_ld_power},
                  {PeakSatParameters::PAY_mcu_33v_currentID, PeakSatParameters::pay_mcu_33v_current},
                  {PeakSatParameters::PAY_fpga_die_temperatureID, PeakSatParameters::pay_fpga_die_temperature},
                  {PeakSatParameters::PAY_fpga_vdd1_voltageID, PeakSatParameters::pay_fpga_vdd1_voltage},
                  {PeakSatParameters::PAY_fpga_vdd18_voltageID, PeakSatParameters::pay_fpga_vdd18_voltage},
                  {PeakSatParameters::PAY_fpga_vdd25_voltageID, PeakSatParameters::pay_fpga_vdd25_voltage},
                  {PeakSatParameters::PAY_seed_ld_incoming_powerID, PeakSatParameters::pay_seed_ld_incoming_power},
                  {PeakSatParameters::PAY_amplifier_output_powerID, PeakSatParameters::pay_amplifier_output_power},
                  {PeakSatParameters::PAY_amplifier_output_reflected_powerID, PeakSatParameters::pay_amplifier_output_reflected_power},
                  {PeakSatParameters::PAY_seed_diode_bias_currentID, PeakSatParameters::pay_seed_diode_bias_current},
                  {PeakSatParameters::PAY_tec_currentID, PeakSatParameters::pay_tec_current},
                  {PeakSatParameters::PAY_ldd_output_currentID, PeakSatParameters::pay_ldd_output_current},
                  {PeakSatParameters::PAY_sd_temperature_violationsID, PeakSatParameters::pay_sd_temperature_violations},
                  {PeakSatParameters::PAY_end_uptimeID, PeakSatParameters::pay_end_uptime},
                  {PeakSatParameters::PAY_responseID, PeakSatParameters::pay_response},
                  {PeakSatParameters::PAY_deviceID, PeakSatParameters::pay_device},
                  {PeakSatParameters::PAY_firmwareID, PeakSatParameters::pay_firmware},
                  {PeakSatParameters::PAY_firmware_is_confirmedID, PeakSatParameters::pay_firmware_is_confirmed},
                  {PeakSatParameters::PAY_bitstreamID, PeakSatParameters::pay_bitstream},
                  {PeakSatParameters::PAY_softcpu_1_firmwareID, PeakSatParameters::pay_softcpu_1_firmware},
                  {PeakSatParameters::PAY_softcpu_2_firmwareID, PeakSatParameters::pay_softcpu_2_firmware},
                  {PeakSatParameters::PAY_softcpu_3_firmwareID, PeakSatParameters::pay_softcpu_3_firmware},
                  {PeakSatParameters::PAY_softcpu_4_firmwareID, PeakSatParameters::pay_softcpu_4_firmware},
                  {PeakSatParameters::PAY_softcpu_5_firmwareID, PeakSatParameters::pay_softcpu_5_firmware},
                  {PeakSatParameters::PAY_softcpu_6_firmwareID, PeakSatParameters::pay_softcpu_6_firmware},
                  {PeakSatParameters::PAY_softcpu_7_firmwareID, PeakSatParameters::pay_softcpu_7_firmware},
                  {PeakSatParameters::PAY_softcpu_8_firmwareID, PeakSatParameters::pay_softcpu_8_firmware},
                  {PeakSatParameters::PAY_boot_countID, PeakSatParameters::pay_boot_count},
                  {PeakSatParameters::PAY_transmission_countID, PeakSatParameters::pay_transmission_count},
                  {PeakSatParameters::PAY_hw_detID, PeakSatParameters::pay_hw_det},
                  {PeakSatParameters::PAY_storage0ID, PeakSatParameters::pay_storage0},
                  {PeakSatParameters::PAY_storage1ID, PeakSatParameters::pay_storage1},
                  {PeakSatParameters::PAY_storage2ID, PeakSatParameters::pay_storage2},
                  {PeakSatParameters::PAY_storage3ID, PeakSatParameters::pay_storage3},
                  {PeakSatParameters::PAY_ldd_faultID, PeakSatParameters::pay_ldd_fault},
                  {PeakSatParameters::PAY_fsm_faultID, PeakSatParameters::pay_fsm_fault},
                  {PeakSatParameters::PAY_fpga_faultID, PeakSatParameters::pay_fpga_fault},
                  {PeakSatParameters::PAY_v_cam_faultID, PeakSatParameters::pay_v_cam_fault},
                  {PeakSatParameters::PAY_sdd_faultID, PeakSatParameters::pay_sdd_fault}
        };
}

#endif